import { Country } from './types'

// Generated by "npm run generate_geodata" in tradle/aws-utils repository
export const countries: { [id: string]: Country } = {
  AW: {
    id: 'AW',
    cca3: 'ABW',
    callingCodes: [
      '297'
    ],
    title: 'Aruba',
    awsRegion: 'us-east-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'us-east-1'
    }
  },
  AF: {
    id: 'AF',
    cca3: 'AFG',
    callingCodes: [
      '93'
    ],
    title: 'Afghanistan',
    awsRegion: 'me-south-1',
    sms: {
      senderID: 0,
      twoWaySMS: false,
      region: 'me-south-1'
    }
  },
  AO: {
    id: 'AO',
    cca3: 'AGO',
    callingCodes: [
      '244'
    ],
    title: 'Angola',
    awsRegion: 'af-south-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'me-south-1'
    }
  },
  AI: {
    id: 'AI',
    cca3: 'AIA',
    callingCodes: [
      '1264'
    ],
    title: 'Anguilla',
    awsRegion: 'us-east-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'us-east-1'
    }
  },
  AX: {
    id: 'AX',
    cca3: 'ALA',
    callingCodes: [
      '35818'
    ],
    title: 'Åland Islands',
    awsRegion: 'eu-north-1'
  },
  AL: {
    id: 'AL',
    cca3: 'ALB',
    callingCodes: [
      '355'
    ],
    title: 'Albania',
    awsRegion: 'eu-south-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'eu-central-1'
    }
  },
  AD: {
    id: 'AD',
    cca3: 'AND',
    callingCodes: [
      '376'
    ],
    title: 'Andorra',
    awsRegion: 'eu-west-3',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'eu-west-3'
    }
  },
  AE: {
    id: 'AE',
    cca3: 'ARE',
    callingCodes: [
      '971'
    ],
    title: 'United Arab Emirates',
    awsRegion: 'me-south-1',
    sms: {
      senderID: 2,
      twoWaySMS: false,
      region: 'me-south-1'
    }
  },
  AR: {
    id: 'AR',
    cca3: 'ARG',
    callingCodes: [
      '54'
    ],
    title: 'Argentina',
    awsRegion: 'sa-east-1',
    sms: {
      senderID: 0,
      twoWaySMS: false,
      region: 'sa-east-1'
    }
  },
  AM: {
    id: 'AM',
    cca3: 'ARM',
    callingCodes: [
      '374'
    ],
    title: 'Armenia',
    awsRegion: 'me-south-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'me-south-1'
    }
  },
  AS: {
    id: 'AS',
    cca3: 'ASM',
    callingCodes: [
      '1684'
    ],
    title: 'American Samoa',
    awsRegion: 'ap-southeast-2'
  },
  AQ: {
    id: 'AQ',
    cca3: 'ATA',
    callingCodes: [],
    title: 'Antarctica',
    awsRegion: 'af-south-1'
  },
  TF: {
    id: 'TF',
    cca3: 'ATF',
    callingCodes: [
      '262'
    ],
    title: 'French Southern and Antarctic Lands',
    awsRegion: 'af-south-1'
  },
  AG: {
    id: 'AG',
    cca3: 'ATG',
    callingCodes: [
      '1268'
    ],
    title: 'Antigua and Barbuda',
    awsRegion: 'us-east-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'us-east-1'
    }
  },
  AU: {
    id: 'AU',
    cca3: 'AUS',
    callingCodes: [
      '61'
    ],
    title: 'Australia',
    awsRegion: 'ap-southeast-2',
    sms: {
      senderID: 1,
      twoWaySMS: true,
      region: 'ap-southeast-2'
    }
  },
  AT: {
    id: 'AT',
    cca3: 'AUT',
    callingCodes: [
      '43'
    ],
    title: 'Austria',
    awsRegion: 'eu-south-1',
    sms: {
      senderID: 1,
      twoWaySMS: true,
      region: 'eu-central-1'
    }
  },
  AZ: {
    id: 'AZ',
    cca3: 'AZE',
    callingCodes: [
      '994'
    ],
    title: 'Azerbaijan',
    awsRegion: 'me-south-1',
    sms: {
      senderID: 0,
      twoWaySMS: false,
      region: 'me-south-1'
    }
  },
  BI: {
    id: 'BI',
    cca3: 'BDI',
    callingCodes: [
      '257'
    ],
    title: 'Burundi',
    awsRegion: 'af-south-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'me-south-1'
    }
  },
  BE: {
    id: 'BE',
    cca3: 'BEL',
    callingCodes: [
      '32'
    ],
    title: 'Belgium',
    awsRegion: 'eu-west-3',
    sms: {
      senderID: 0,
      twoWaySMS: true,
      region: 'eu-west-3'
    }
  },
  BJ: {
    id: 'BJ',
    cca3: 'BEN',
    callingCodes: [
      '229'
    ],
    title: 'Benin',
    awsRegion: 'eu-south-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'eu-west-3'
    }
  },
  BF: {
    id: 'BF',
    cca3: 'BFA',
    callingCodes: [
      '226'
    ],
    title: 'Burkina Faso',
    awsRegion: 'eu-south-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'eu-west-3'
    }
  },
  BD: {
    id: 'BD',
    cca3: 'BGD',
    callingCodes: [
      '880'
    ],
    title: 'Bangladesh',
    awsRegion: 'ap-south-1',
    sms: {
      senderID: 0,
      twoWaySMS: false,
      region: 'ap-south-1'
    }
  },
  BG: {
    id: 'BG',
    cca3: 'BGR',
    callingCodes: [
      '359'
    ],
    title: 'Bulgaria',
    awsRegion: 'eu-south-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'eu-central-1'
    }
  },
  BH: {
    id: 'BH',
    cca3: 'BHR',
    callingCodes: [
      '973'
    ],
    title: 'Bahrain',
    awsRegion: 'me-south-1',
    sms: {
      senderID: 1,
      twoWaySMS: true,
      region: 'me-south-1'
    }
  },
  BS: {
    id: 'BS',
    cca3: 'BHS',
    callingCodes: [
      '1242'
    ],
    title: 'Bahamas',
    awsRegion: 'us-east-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'us-east-1'
    }
  },
  BA: {
    id: 'BA',
    cca3: 'BIH',
    callingCodes: [
      '387'
    ],
    title: 'Bosnia and Herzegovina',
    awsRegion: 'eu-south-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'eu-central-1'
    }
  },
  BL: {
    id: 'BL',
    cca3: 'BLM',
    callingCodes: [
      '590'
    ],
    title: 'Saint Barthélemy',
    awsRegion: 'us-east-1'
  },
  SH: {
    id: 'SH',
    cca3: 'SHN',
    callingCodes: [
      '290',
      '247'
    ],
    title: 'Saint Helena, Ascension and Tristan da Cunha',
    awsRegion: 'af-south-1'
  },
  BY: {
    id: 'BY',
    cca3: 'BLR',
    callingCodes: [
      '375'
    ],
    title: 'Belarus',
    awsRegion: 'eu-north-1',
    sms: {
      senderID: 2,
      twoWaySMS: false,
      region: 'eu-north-1'
    }
  },
  BZ: {
    id: 'BZ',
    cca3: 'BLZ',
    callingCodes: [
      '501'
    ],
    title: 'Belize',
    awsRegion: 'us-east-2',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'us-east-2'
    }
  },
  BM: {
    id: 'BM',
    cca3: 'BMU',
    callingCodes: [
      '1441'
    ],
    title: 'Bermuda',
    awsRegion: 'us-east-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'us-east-1'
    }
  },
  BO: {
    id: 'BO',
    cca3: 'BOL',
    callingCodes: [
      '591'
    ],
    title: 'Bolivia',
    awsRegion: 'sa-east-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'sa-east-1'
    }
  },
  BQ: {
    id: 'BQ',
    cca3: 'BES',
    callingCodes: [
      '599'
    ],
    title: 'Caribbean Netherlands',
    awsRegion: 'us-east-1'
  },
  BR: {
    id: 'BR',
    cca3: 'BRA',
    callingCodes: [
      '55'
    ],
    title: 'Brazil',
    awsRegion: 'sa-east-1',
    sms: {
      senderID: 0,
      twoWaySMS: true,
      region: 'sa-east-1'
    }
  },
  BB: {
    id: 'BB',
    cca3: 'BRB',
    callingCodes: [
      '1246'
    ],
    title: 'Barbados',
    awsRegion: 'us-east-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'us-east-1'
    }
  },
  BN: {
    id: 'BN',
    cca3: 'BRN',
    callingCodes: [
      '673'
    ],
    title: 'Brunei',
    awsRegion: 'ap-southeast-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'ap-southeast-1'
    }
  },
  BT: {
    id: 'BT',
    cca3: 'BTN',
    callingCodes: [
      '975'
    ],
    title: 'Bhutan',
    awsRegion: 'ap-south-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'ap-south-1'
    }
  },
  BV: {
    id: 'BV',
    cca3: 'BVT',
    callingCodes: [
      '47'
    ],
    title: 'Bouvet Island',
    awsRegion: 'af-south-1'
  },
  BW: {
    id: 'BW',
    cca3: 'BWA',
    callingCodes: [
      '267'
    ],
    title: 'Botswana',
    awsRegion: 'af-south-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'me-south-1'
    }
  },
  CF: {
    id: 'CF',
    cca3: 'CAF',
    callingCodes: [
      '236'
    ],
    title: 'Central African Republic',
    awsRegion: 'me-south-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'me-south-1'
    }
  },
  CA: {
    id: 'CA',
    cca3: 'CAN',
    callingCodes: [
      '1'
    ],
    title: 'Canada',
    awsRegion: 'ca-central-1',
    sms: {
      senderID: 0,
      twoWaySMS: true,
      region: 'ca-central-1'
    }
  },
  CC: {
    id: 'CC',
    cca3: 'CCK',
    callingCodes: [
      '61'
    ],
    title: 'Cocos (Keeling) Islands',
    awsRegion: 'ap-southeast-1'
  },
  CH: {
    id: 'CH',
    cca3: 'CHE',
    callingCodes: [
      '41'
    ],
    title: 'Switzerland',
    awsRegion: 'eu-south-1',
    sms: {
      senderID: 1,
      twoWaySMS: true,
      region: 'eu-central-1'
    }
  },
  CL: {
    id: 'CL',
    cca3: 'CHL',
    callingCodes: [
      '56'
    ],
    title: 'Chile',
    awsRegion: 'sa-east-1',
    sms: {
      senderID: 0,
      twoWaySMS: true,
      region: 'sa-east-1'
    }
  },
  CN: {
    id: 'CN',
    cca3: 'CHN',
    callingCodes: [
      '86'
    ],
    title: 'China',
    awsRegion: 'ap-east-1',
    sms: {
      senderID: 0,
      twoWaySMS: false,
      region: 'ap-northeast-1'
    }
  },
  CI: {
    id: 'CI',
    cca3: 'CIV',
    callingCodes: [
      '225'
    ],
    title: 'Ivory Coast',
    awsRegion: 'eu-south-1',
    sms: {
      senderID: 0,
      twoWaySMS: false,
      region: 'eu-west-3'
    }
  },
  CM: {
    id: 'CM',
    cca3: 'CMR',
    callingCodes: [
      '237'
    ],
    title: 'Cameroon',
    awsRegion: 'eu-south-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'me-south-1'
    }
  },
  CD: {
    id: 'CD',
    cca3: 'COD',
    callingCodes: [
      '243'
    ],
    title: 'DR Congo',
    awsRegion: 'af-south-1',
    sms: {
      senderID: 0,
      twoWaySMS: false,
      region: 'me-south-1'
    }
  },
  CG: {
    id: 'CG',
    cca3: 'COG',
    callingCodes: [
      '242'
    ],
    title: 'Republic of the Congo',
    awsRegion: 'af-south-1',
    sms: {
      senderID: 0,
      twoWaySMS: false,
      region: 'me-south-1'
    }
  },
  CK: {
    id: 'CK',
    cca3: 'COK',
    callingCodes: [
      '682'
    ],
    title: 'Cook Islands',
    awsRegion: 'ap-southeast-2',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'ap-southeast-2'
    }
  },
  CO: {
    id: 'CO',
    cca3: 'COL',
    callingCodes: [
      '57'
    ],
    title: 'Colombia',
    awsRegion: 'us-east-1',
    sms: {
      senderID: 0,
      twoWaySMS: false,
      region: 'us-east-1'
    }
  },
  KM: {
    id: 'KM',
    cca3: 'COM',
    callingCodes: [
      '269'
    ],
    title: 'Comoros',
    awsRegion: 'af-south-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'me-south-1'
    }
  },
  CV: {
    id: 'CV',
    cca3: 'CPV',
    callingCodes: [
      '238'
    ],
    title: 'Cape Verde',
    awsRegion: 'eu-west-3',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'eu-west-3'
    }
  },
  CR: {
    id: 'CR',
    cca3: 'CRI',
    callingCodes: [
      '506'
    ],
    title: 'Costa Rica',
    awsRegion: 'us-east-1',
    sms: {
      senderID: 0,
      twoWaySMS: false,
      region: 'us-east-1'
    }
  },
  CU: {
    id: 'CU',
    cca3: 'CUB',
    callingCodes: [
      '53'
    ],
    title: 'Cuba',
    awsRegion: 'us-east-1'
  },
  CW: {
    id: 'CW',
    cca3: 'CUW',
    callingCodes: [
      '599'
    ],
    title: 'Curaçao',
    awsRegion: 'us-east-1'
  },
  CX: {
    id: 'CX',
    cca3: 'CXR',
    callingCodes: [
      '61'
    ],
    title: 'Christmas Island',
    awsRegion: 'ap-southeast-1'
  },
  KY: {
    id: 'KY',
    cca3: 'CYM',
    callingCodes: [
      '1345'
    ],
    title: 'Cayman Islands',
    awsRegion: 'us-east-1',
    sms: {
      senderID: 0,
      twoWaySMS: false,
      region: 'us-east-1'
    }
  },
  CY: {
    id: 'CY',
    cca3: 'CYP',
    callingCodes: [
      '357'
    ],
    title: 'Cyprus',
    awsRegion: 'me-south-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'me-south-1'
    }
  },
  CZ: {
    id: 'CZ',
    cca3: 'CZE',
    callingCodes: [
      '420'
    ],
    title: 'Czechia',
    awsRegion: 'eu-central-1',
    sms: {
      senderID: 0,
      twoWaySMS: true,
      region: 'eu-central-1'
    }
  },
  DE: {
    id: 'DE',
    cca3: 'DEU',
    callingCodes: [
      '49'
    ],
    title: 'Germany',
    awsRegion: 'eu-central-1',
    sms: {
      senderID: 1,
      twoWaySMS: true,
      region: 'eu-central-1'
    }
  },
  DJ: {
    id: 'DJ',
    cca3: 'DJI',
    callingCodes: [
      '253'
    ],
    title: 'Djibouti',
    awsRegion: 'me-south-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'me-south-1'
    }
  },
  DM: {
    id: 'DM',
    cca3: 'DMA',
    callingCodes: [
      '1767'
    ],
    title: 'Dominica',
    awsRegion: 'us-east-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'us-east-1'
    }
  },
  DK: {
    id: 'DK',
    cca3: 'DNK',
    callingCodes: [
      '45'
    ],
    title: 'Denmark',
    awsRegion: 'eu-north-1',
    sms: {
      senderID: 1,
      twoWaySMS: true,
      region: 'eu-north-1'
    }
  },
  DO: {
    id: 'DO',
    cca3: 'DOM',
    callingCodes: [
      '1809',
      '1829',
      '1849'
    ],
    title: 'Dominican Republic',
    awsRegion: 'us-east-1',
    sms: {
      senderID: 0,
      twoWaySMS: false,
      region: 'us-east-1'
    }
  },
  DZ: {
    id: 'DZ',
    cca3: 'DZA',
    callingCodes: [
      '213'
    ],
    title: 'Algeria',
    awsRegion: 'eu-south-1',
    sms: {
      senderID: 0,
      twoWaySMS: false,
      region: 'eu-west-3'
    }
  },
  EC: {
    id: 'EC',
    cca3: 'ECU',
    callingCodes: [
      '593'
    ],
    title: 'Ecuador',
    awsRegion: 'sa-east-1',
    sms: {
      senderID: 0,
      twoWaySMS: false,
      region: 'sa-east-1'
    }
  },
  EG: {
    id: 'EG',
    cca3: 'EGY',
    callingCodes: [
      '20'
    ],
    title: 'Egypt',
    awsRegion: 'me-south-1',
    sms: {
      senderID: 2,
      twoWaySMS: false,
      region: 'me-south-1'
    }
  },
  ER: {
    id: 'ER',
    cca3: 'ERI',
    callingCodes: [
      '291'
    ],
    title: 'Eritrea',
    awsRegion: 'me-south-1'
  },
  EH: {
    id: 'EH',
    cca3: 'ESH',
    callingCodes: [
      '2125288',
      '2125289'
    ],
    title: 'Western Sahara',
    awsRegion: 'eu-west-3'
  },
  ES: {
    id: 'ES',
    cca3: 'ESP',
    callingCodes: [
      '34'
    ],
    title: 'Spain',
    awsRegion: 'eu-west-3',
    sms: {
      senderID: 1,
      twoWaySMS: true,
      region: 'eu-west-3'
    }
  },
  EE: {
    id: 'EE',
    cca3: 'EST',
    callingCodes: [
      '372'
    ],
    title: 'Estonia',
    awsRegion: 'eu-north-1',
    sms: {
      senderID: 1,
      twoWaySMS: true,
      region: 'eu-north-1'
    }
  },
  ET: {
    id: 'ET',
    cca3: 'ETH',
    callingCodes: [
      '251'
    ],
    title: 'Ethiopia',
    awsRegion: 'me-south-1',
    sms: {
      senderID: 0,
      twoWaySMS: false,
      region: 'me-south-1'
    }
  },
  FI: {
    id: 'FI',
    cca3: 'FIN',
    callingCodes: [
      '358'
    ],
    title: 'Finland',
    awsRegion: 'eu-north-1',
    sms: {
      senderID: 1,
      twoWaySMS: true,
      region: 'eu-north-1'
    }
  },
  FJ: {
    id: 'FJ',
    cca3: 'FJI',
    callingCodes: [
      '679'
    ],
    title: 'Fiji',
    awsRegion: 'ap-southeast-2',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'ap-southeast-2'
    }
  },
  FK: {
    id: 'FK',
    cca3: 'FLK',
    callingCodes: [
      '500'
    ],
    title: 'Falkland Islands',
    awsRegion: 'sa-east-1'
  },
  FR: {
    id: 'FR',
    cca3: 'FRA',
    callingCodes: [
      '33'
    ],
    title: 'France',
    awsRegion: 'eu-west-3',
    sms: {
      senderID: 1,
      twoWaySMS: true,
      region: 'eu-west-3'
    }
  },
  FO: {
    id: 'FO',
    cca3: 'FRO',
    callingCodes: [
      '298'
    ],
    title: 'Faroe Islands',
    awsRegion: 'eu-west-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'eu-west-1'
    }
  },
  FM: {
    id: 'FM',
    cca3: 'FSM',
    callingCodes: [
      '691'
    ],
    title: 'Micronesia',
    awsRegion: 'ap-northeast-1'
  },
  GA: {
    id: 'GA',
    cca3: 'GAB',
    callingCodes: [
      '241'
    ],
    title: 'Gabon',
    awsRegion: 'af-south-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'me-south-1'
    }
  },
  GB: {
    id: 'GB',
    cca3: 'GBR',
    callingCodes: [
      '44'
    ],
    title: 'United Kingdom',
    awsRegion: 'eu-west-1',
    sms: {
      senderID: 1,
      twoWaySMS: true,
      region: 'eu-west-1'
    }
  },
  GE: {
    id: 'GE',
    cca3: 'GEO',
    callingCodes: [
      '995'
    ],
    title: 'Georgia',
    awsRegion: 'me-south-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'me-south-1'
    }
  },
  GG: {
    id: 'GG',
    cca3: 'GGY',
    callingCodes: [
      '44'
    ],
    title: 'Guernsey',
    awsRegion: 'eu-west-2'
  },
  GH: {
    id: 'GH',
    cca3: 'GHA',
    callingCodes: [
      '233'
    ],
    title: 'Ghana',
    awsRegion: 'eu-south-1',
    sms: {
      senderID: 0,
      twoWaySMS: false,
      region: 'eu-west-3'
    }
  },
  GI: {
    id: 'GI',
    cca3: 'GIB',
    callingCodes: [
      '350'
    ],
    title: 'Gibraltar',
    awsRegion: 'eu-west-3',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'eu-west-3'
    }
  },
  GN: {
    id: 'GN',
    cca3: 'GIN',
    callingCodes: [
      '224'
    ],
    title: 'Guinea',
    awsRegion: 'eu-south-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'eu-west-3'
    }
  },
  GP: {
    id: 'GP',
    cca3: 'GLP',
    callingCodes: [
      '590'
    ],
    title: 'Guadeloupe',
    awsRegion: 'us-east-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'us-east-1'
    }
  },
  GM: {
    id: 'GM',
    cca3: 'GMB',
    callingCodes: [
      '220'
    ],
    title: 'Gambia',
    awsRegion: 'eu-west-3',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'eu-west-3'
    }
  },
  GW: {
    id: 'GW',
    cca3: 'GNB',
    callingCodes: [
      '245'
    ],
    title: 'Guinea-Bissau',
    awsRegion: 'eu-south-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'eu-west-3'
    }
  },
  GQ: {
    id: 'GQ',
    cca3: 'GNQ',
    callingCodes: [
      '240'
    ],
    title: 'Equatorial Guinea',
    awsRegion: 'af-south-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'me-south-1'
    }
  },
  GR: {
    id: 'GR',
    cca3: 'GRC',
    callingCodes: [
      '30'
    ],
    title: 'Greece',
    awsRegion: 'eu-south-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'eu-central-1'
    }
  },
  GD: {
    id: 'GD',
    cca3: 'GRD',
    callingCodes: [
      '1473'
    ],
    title: 'Grenada',
    awsRegion: 'us-east-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'us-east-1'
    }
  },
  GL: {
    id: 'GL',
    cca3: 'GRL',
    callingCodes: [
      '299'
    ],
    title: 'Greenland',
    awsRegion: 'eu-west-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'eu-west-1'
    }
  },
  GT: {
    id: 'GT',
    cca3: 'GTM',
    callingCodes: [
      '502'
    ],
    title: 'Guatemala',
    awsRegion: 'us-east-2',
    sms: {
      senderID: 0,
      twoWaySMS: true,
      region: 'us-east-2'
    }
  },
  GF: {
    id: 'GF',
    cca3: 'GUF',
    callingCodes: [
      '594'
    ],
    title: 'French Guiana',
    awsRegion: 'sa-east-1',
    sms: {
      senderID: 0,
      twoWaySMS: false,
      region: 'sa-east-1'
    }
  },
  GU: {
    id: 'GU',
    cca3: 'GUM',
    callingCodes: [
      '1671'
    ],
    title: 'Guam',
    awsRegion: 'ap-northeast-1',
    sms: {
      senderID: 0,
      twoWaySMS: false,
      region: 'ap-northeast-1'
    }
  },
  GY: {
    id: 'GY',
    cca3: 'GUY',
    callingCodes: [
      '592'
    ],
    title: 'Guyana',
    awsRegion: 'sa-east-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'sa-east-1'
    }
  },
  HK: {
    id: 'HK',
    cca3: 'HKG',
    callingCodes: [
      '852'
    ],
    title: 'Hong Kong',
    awsRegion: 'ap-east-1',
    sms: {
      senderID: 1,
      twoWaySMS: true,
      region: 'ap-southeast-1'
    }
  },
  HM: {
    id: 'HM',
    cca3: 'HMD',
    callingCodes: [
      ''
    ],
    title: 'Heard Island and McDonald Islands',
    awsRegion: 'af-south-1'
  },
  HN: {
    id: 'HN',
    cca3: 'HND',
    callingCodes: [
      '504'
    ],
    title: 'Honduras',
    awsRegion: 'us-east-1',
    sms: {
      senderID: 0,
      twoWaySMS: true,
      region: 'us-east-1'
    }
  },
  HR: {
    id: 'HR',
    cca3: 'HRV',
    callingCodes: [
      '385'
    ],
    title: 'Croatia',
    awsRegion: 'eu-south-1',
    sms: {
      senderID: 0,
      twoWaySMS: true,
      region: 'eu-central-1'
    }
  },
  HT: {
    id: 'HT',
    cca3: 'HTI',
    callingCodes: [
      '509'
    ],
    title: 'Haiti',
    awsRegion: 'us-east-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'us-east-1'
    }
  },
  HU: {
    id: 'HU',
    cca3: 'HUN',
    callingCodes: [
      '36'
    ],
    title: 'Hungary',
    awsRegion: 'eu-south-1',
    sms: {
      senderID: 0,
      twoWaySMS: true,
      region: 'eu-central-1'
    }
  },
  ID: {
    id: 'ID',
    cca3: 'IDN',
    callingCodes: [
      '62'
    ],
    title: 'Indonesia',
    awsRegion: 'ap-southeast-1',
    sms: {
      senderID: 0,
      twoWaySMS: false,
      region: 'ap-southeast-1'
    }
  },
  IM: {
    id: 'IM',
    cca3: 'IMN',
    callingCodes: [
      '44'
    ],
    title: 'Isle of Man',
    awsRegion: 'eu-west-1'
  },
  IN: {
    id: 'IN',
    cca3: 'IND',
    callingCodes: [
      '91'
    ],
    title: 'India',
    awsRegion: 'ap-south-1',
    sms: {
      senderID: 2,
      twoWaySMS: true,
      region: 'ap-south-1'
    }
  },
  IO: {
    id: 'IO',
    cca3: 'IOT',
    callingCodes: [
      '246'
    ],
    title: 'British Indian Ocean Territory',
    awsRegion: 'ap-south-1'
  },
  IE: {
    id: 'IE',
    cca3: 'IRL',
    callingCodes: [
      '353'
    ],
    title: 'Ireland',
    awsRegion: 'eu-west-1',
    sms: {
      senderID: 1,
      twoWaySMS: true,
      region: 'eu-west-1'
    }
  },
  IR: {
    id: 'IR',
    cca3: 'IRN',
    callingCodes: [
      '98'
    ],
    title: 'Iran',
    awsRegion: 'me-south-1'
  },
  IQ: {
    id: 'IQ',
    cca3: 'IRQ',
    callingCodes: [
      '964'
    ],
    title: 'Iraq',
    awsRegion: 'me-south-1',
    sms: {
      senderID: 0,
      twoWaySMS: false,
      region: 'me-south-1'
    }
  },
  IS: {
    id: 'IS',
    cca3: 'ISL',
    callingCodes: [
      '354'
    ],
    title: 'Iceland',
    awsRegion: 'eu-west-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'eu-west-1'
    }
  },
  IL: {
    id: 'IL',
    cca3: 'ISR',
    callingCodes: [
      '972'
    ],
    title: 'Israel',
    awsRegion: 'me-south-1',
    sms: {
      senderID: 1,
      twoWaySMS: true,
      region: 'me-south-1'
    }
  },
  IT: {
    id: 'IT',
    cca3: 'ITA',
    callingCodes: [
      '39'
    ],
    title: 'Italy',
    awsRegion: 'eu-south-1',
    sms: {
      senderID: 1,
      twoWaySMS: true,
      region: 'eu-central-1'
    }
  },
  JM: {
    id: 'JM',
    cca3: 'JAM',
    callingCodes: [
      '1876'
    ],
    title: 'Jamaica',
    awsRegion: 'us-east-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'us-east-1'
    }
  },
  JE: {
    id: 'JE',
    cca3: 'JEY',
    callingCodes: [
      '44'
    ],
    title: 'Jersey',
    awsRegion: 'eu-west-2'
  },
  JO: {
    id: 'JO',
    cca3: 'JOR',
    callingCodes: [
      '962'
    ],
    title: 'Jordan',
    awsRegion: 'me-south-1',
    sms: {
      senderID: 2,
      twoWaySMS: false,
      region: 'me-south-1'
    }
  },
  JP: {
    id: 'JP',
    cca3: 'JPN',
    callingCodes: [
      '81'
    ],
    title: 'Japan',
    awsRegion: 'ap-northeast-1',
    sms: {
      senderID: 0,
      twoWaySMS: true,
      region: 'ap-northeast-1'
    }
  },
  KZ: {
    id: 'KZ',
    cca3: 'KAZ',
    callingCodes: [
      '76',
      '77'
    ],
    title: 'Kazakhstan',
    awsRegion: 'me-south-1',
    sms: {
      senderID: 0,
      twoWaySMS: false,
      region: 'me-south-1'
    }
  },
  KE: {
    id: 'KE',
    cca3: 'KEN',
    callingCodes: [
      '254'
    ],
    title: 'Kenya',
    awsRegion: 'me-south-1',
    sms: {
      senderID: 0,
      twoWaySMS: false,
      region: 'me-south-1'
    }
  },
  KG: {
    id: 'KG',
    cca3: 'KGZ',
    callingCodes: [
      '996'
    ],
    title: 'Kyrgyzstan',
    awsRegion: 'ap-south-1',
    sms: {
      senderID: 0,
      twoWaySMS: false,
      region: 'ap-south-1'
    }
  },
  KH: {
    id: 'KH',
    cca3: 'KHM',
    callingCodes: [
      '855'
    ],
    title: 'Cambodia',
    awsRegion: 'ap-southeast-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'ap-southeast-1'
    }
  },
  KI: {
    id: 'KI',
    cca3: 'KIR',
    callingCodes: [
      '686'
    ],
    title: 'Kiribati',
    awsRegion: 'ap-southeast-2',
    sms: {
      senderID: 0,
      twoWaySMS: false,
      region: 'ap-southeast-2'
    }
  },
  KN: {
    id: 'KN',
    cca3: 'KNA',
    callingCodes: [
      '1869'
    ],
    title: 'Saint Kitts and Nevis',
    awsRegion: 'us-east-1',
    sms: {
      senderID: 0,
      twoWaySMS: false,
      region: 'us-east-1'
    }
  },
  KR: {
    id: 'KR',
    cca3: 'KOR',
    callingCodes: [
      '82'
    ],
    title: 'South Korea',
    awsRegion: 'ap-northeast-2',
    sms: {
      senderID: 0,
      twoWaySMS: false,
      region: 'ap-northeast-1'
    }
  },
  XK: {
    id: 'XK',
    cca3: 'UNK',
    callingCodes: [
      '383'
    ],
    title: 'Kosovo',
    awsRegion: 'eu-south-1'
  },
  KW: {
    id: 'KW',
    cca3: 'KWT',
    callingCodes: [
      '965'
    ],
    title: 'Kuwait',
    awsRegion: 'me-south-1',
    sms: {
      senderID: 2,
      twoWaySMS: false,
      region: 'me-south-1'
    }
  },
  LA: {
    id: 'LA',
    cca3: 'LAO',
    callingCodes: [
      '856'
    ],
    title: 'Laos',
    awsRegion: 'ap-east-1',
    sms: {
      senderID: 0,
      twoWaySMS: false,
      region: 'ap-southeast-1'
    }
  },
  LB: {
    id: 'LB',
    cca3: 'LBN',
    callingCodes: [
      '961'
    ],
    title: 'Lebanon',
    awsRegion: 'me-south-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'me-south-1'
    }
  },
  LR: {
    id: 'LR',
    cca3: 'LBR',
    callingCodes: [
      '231'
    ],
    title: 'Liberia',
    awsRegion: 'eu-south-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'eu-west-3'
    }
  },
  LY: {
    id: 'LY',
    cca3: 'LBY',
    callingCodes: [
      '218'
    ],
    title: 'Libya',
    awsRegion: 'eu-south-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'eu-central-1'
    }
  },
  LC: {
    id: 'LC',
    cca3: 'LCA',
    callingCodes: [
      '1758'
    ],
    title: 'Saint Lucia',
    awsRegion: 'us-east-1',
    sms: {
      senderID: 0,
      twoWaySMS: false,
      region: 'us-east-1'
    }
  },
  LI: {
    id: 'LI',
    cca3: 'LIE',
    callingCodes: [
      '423'
    ],
    title: 'Liechtenstein',
    awsRegion: 'eu-south-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'eu-central-1'
    }
  },
  LK: {
    id: 'LK',
    cca3: 'LKA',
    callingCodes: [
      '94'
    ],
    title: 'Sri Lanka',
    awsRegion: 'ap-south-1',
    sms: {
      senderID: 2,
      twoWaySMS: false,
      region: 'ap-south-1'
    }
  },
  LS: {
    id: 'LS',
    cca3: 'LSO',
    callingCodes: [
      '266'
    ],
    title: 'Lesotho',
    awsRegion: 'af-south-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'me-south-1'
    }
  },
  LT: {
    id: 'LT',
    cca3: 'LTU',
    callingCodes: [
      '370'
    ],
    title: 'Lithuania',
    awsRegion: 'eu-north-1',
    sms: {
      senderID: 1,
      twoWaySMS: true,
      region: 'eu-north-1'
    }
  },
  LU: {
    id: 'LU',
    cca3: 'LUX',
    callingCodes: [
      '352'
    ],
    title: 'Luxembourg',
    awsRegion: 'eu-central-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'eu-central-1'
    }
  },
  LV: {
    id: 'LV',
    cca3: 'LVA',
    callingCodes: [
      '371'
    ],
    title: 'Latvia',
    awsRegion: 'eu-north-1',
    sms: {
      senderID: 1,
      twoWaySMS: true,
      region: 'eu-north-1'
    }
  },
  MO: {
    id: 'MO',
    cca3: 'MAC',
    callingCodes: [
      '853'
    ],
    title: 'Macau',
    awsRegion: 'ap-east-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'ap-southeast-1'
    }
  },
  MF: {
    id: 'MF',
    cca3: 'MAF',
    callingCodes: [
      '590'
    ],
    title: 'Saint Martin',
    awsRegion: 'us-east-1'
  },
  MA: {
    id: 'MA',
    cca3: 'MAR',
    callingCodes: [
      '212'
    ],
    title: 'Morocco',
    awsRegion: 'eu-south-1',
    sms: {
      senderID: 0,
      twoWaySMS: false,
      region: 'eu-west-3'
    }
  },
  MC: {
    id: 'MC',
    cca3: 'MCO',
    callingCodes: [
      '377'
    ],
    title: 'Monaco',
    awsRegion: 'eu-south-1',
    sms: {
      senderID: 0,
      twoWaySMS: false,
      region: 'eu-west-3'
    }
  },
  MD: {
    id: 'MD',
    cca3: 'MDA',
    callingCodes: [
      '373'
    ],
    title: 'Moldova',
    awsRegion: 'eu-central-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'eu-central-1'
    }
  },
  MG: {
    id: 'MG',
    cca3: 'MDG',
    callingCodes: [
      '261'
    ],
    title: 'Madagascar',
    awsRegion: 'af-south-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'me-south-1'
    }
  },
  MV: {
    id: 'MV',
    cca3: 'MDV',
    callingCodes: [
      '960'
    ],
    title: 'Maldives',
    awsRegion: 'ap-south-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'ap-south-1'
    }
  },
  MX: {
    id: 'MX',
    cca3: 'MEX',
    callingCodes: [
      '52'
    ],
    title: 'Mexico',
    awsRegion: 'us-west-1',
    sms: {
      senderID: 0,
      twoWaySMS: true,
      region: 'us-west-1'
    }
  },
  MH: {
    id: 'MH',
    cca3: 'MHL',
    callingCodes: [
      '692'
    ],
    title: 'Marshall Islands',
    awsRegion: 'ap-northeast-1'
  },
  MK: {
    id: 'MK',
    cca3: 'MKD',
    callingCodes: [
      '389'
    ],
    title: 'North Macedonia',
    awsRegion: 'eu-south-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'eu-central-1'
    }
  },
  ML: {
    id: 'ML',
    cca3: 'MLI',
    callingCodes: [
      '223'
    ],
    title: 'Mali',
    awsRegion: 'eu-south-1',
    sms: {
      senderID: 0,
      twoWaySMS: false,
      region: 'eu-west-3'
    }
  },
  MT: {
    id: 'MT',
    cca3: 'MLT',
    callingCodes: [
      '356'
    ],
    title: 'Malta',
    awsRegion: 'eu-south-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'eu-central-1'
    }
  },
  MM: {
    id: 'MM',
    cca3: 'MMR',
    callingCodes: [
      '95'
    ],
    title: 'Myanmar',
    awsRegion: 'ap-east-1',
    sms: {
      senderID: 0,
      twoWaySMS: false,
      region: 'ap-southeast-1'
    }
  },
  ME: {
    id: 'ME',
    cca3: 'MNE',
    callingCodes: [
      '382'
    ],
    title: 'Montenegro',
    awsRegion: 'eu-south-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'eu-central-1'
    }
  },
  MN: {
    id: 'MN',
    cca3: 'MNG',
    callingCodes: [
      '976'
    ],
    title: 'Mongolia',
    awsRegion: 'ap-northeast-2',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'ap-northeast-1'
    }
  },
  MP: {
    id: 'MP',
    cca3: 'MNP',
    callingCodes: [
      '1670'
    ],
    title: 'Northern Mariana Islands',
    awsRegion: 'ap-northeast-1'
  },
  MZ: {
    id: 'MZ',
    cca3: 'MOZ',
    callingCodes: [
      '258'
    ],
    title: 'Mozambique',
    awsRegion: 'af-south-1',
    sms: {
      senderID: 0,
      twoWaySMS: false,
      region: 'me-south-1'
    }
  },
  MR: {
    id: 'MR',
    cca3: 'MRT',
    callingCodes: [
      '222'
    ],
    title: 'Mauritania',
    awsRegion: 'eu-west-3',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'eu-west-3'
    }
  },
  MS: {
    id: 'MS',
    cca3: 'MSR',
    callingCodes: [
      '1664'
    ],
    title: 'Montserrat',
    awsRegion: 'us-east-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'us-east-1'
    }
  },
  MQ: {
    id: 'MQ',
    cca3: 'MTQ',
    callingCodes: [
      '596'
    ],
    title: 'Martinique',
    awsRegion: 'us-east-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'us-east-1'
    }
  },
  MU: {
    id: 'MU',
    cca3: 'MUS',
    callingCodes: [
      '230'
    ],
    title: 'Mauritius',
    awsRegion: 'af-south-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'ap-south-1'
    }
  },
  MW: {
    id: 'MW',
    cca3: 'MWI',
    callingCodes: [
      '265'
    ],
    title: 'Malawi',
    awsRegion: 'af-south-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'me-south-1'
    }
  },
  MY: {
    id: 'MY',
    cca3: 'MYS',
    callingCodes: [
      '60'
    ],
    title: 'Malaysia',
    awsRegion: 'ap-southeast-1',
    sms: {
      senderID: 0,
      twoWaySMS: true,
      region: 'ap-southeast-1'
    }
  },
  YT: {
    id: 'YT',
    cca3: 'MYT',
    callingCodes: [
      '262'
    ],
    title: 'Mayotte',
    awsRegion: 'af-south-1'
  },
  NA: {
    id: 'NA',
    cca3: 'NAM',
    callingCodes: [
      '264'
    ],
    title: 'Namibia',
    awsRegion: 'af-south-1',
    sms: {
      senderID: 0,
      twoWaySMS: false,
      region: 'me-south-1'
    }
  },
  NC: {
    id: 'NC',
    cca3: 'NCL',
    callingCodes: [
      '687'
    ],
    title: 'New Caledonia',
    awsRegion: 'ap-southeast-2',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'ap-southeast-2'
    }
  },
  NE: {
    id: 'NE',
    cca3: 'NER',
    callingCodes: [
      '227'
    ],
    title: 'Niger',
    awsRegion: 'eu-south-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'eu-west-3'
    }
  },
  NF: {
    id: 'NF',
    cca3: 'NFK',
    callingCodes: [
      '672'
    ],
    title: 'Norfolk Island',
    awsRegion: 'ap-southeast-2'
  },
  NG: {
    id: 'NG',
    cca3: 'NGA',
    callingCodes: [
      '234'
    ],
    title: 'Nigeria',
    awsRegion: 'eu-south-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'eu-west-3'
    }
  },
  NI: {
    id: 'NI',
    cca3: 'NIC',
    callingCodes: [
      '505'
    ],
    title: 'Nicaragua',
    awsRegion: 'us-east-1',
    sms: {
      senderID: 0,
      twoWaySMS: false,
      region: 'us-east-1'
    }
  },
  NU: {
    id: 'NU',
    cca3: 'NIU',
    callingCodes: [
      '683'
    ],
    title: 'Niue',
    awsRegion: 'ap-southeast-2'
  },
  NL: {
    id: 'NL',
    cca3: 'NLD',
    callingCodes: [
      '31'
    ],
    title: 'Netherlands',
    awsRegion: 'eu-central-1',
    sms: {
      senderID: 1,
      twoWaySMS: true,
      region: 'eu-central-1'
    }
  },
  NO: {
    id: 'NO',
    cca3: 'NOR',
    callingCodes: [
      '47'
    ],
    title: 'Norway',
    awsRegion: 'eu-north-1',
    sms: {
      senderID: 1,
      twoWaySMS: true,
      region: 'eu-north-1'
    }
  },
  NP: {
    id: 'NP',
    cca3: 'NPL',
    callingCodes: [
      '977'
    ],
    title: 'Nepal',
    awsRegion: 'ap-south-1',
    sms: {
      senderID: 0,
      twoWaySMS: false,
      region: 'ap-south-1'
    }
  },
  NR: {
    id: 'NR',
    cca3: 'NRU',
    callingCodes: [
      '674'
    ],
    title: 'Nauru',
    awsRegion: 'ap-southeast-2'
  },
  NZ: {
    id: 'NZ',
    cca3: 'NZL',
    callingCodes: [
      '64'
    ],
    title: 'New Zealand',
    awsRegion: 'ap-southeast-2',
    sms: {
      senderID: 0,
      twoWaySMS: true,
      region: 'ap-southeast-2'
    }
  },
  OM: {
    id: 'OM',
    cca3: 'OMN',
    callingCodes: [
      '968'
    ],
    title: 'Oman',
    awsRegion: 'me-south-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'me-south-1'
    }
  },
  PK: {
    id: 'PK',
    cca3: 'PAK',
    callingCodes: [
      '92'
    ],
    title: 'Pakistan',
    awsRegion: 'ap-south-1',
    sms: {
      senderID: 0,
      twoWaySMS: false,
      region: 'ap-south-1'
    }
  },
  PA: {
    id: 'PA',
    cca3: 'PAN',
    callingCodes: [
      '507'
    ],
    title: 'Panama',
    awsRegion: 'us-east-1',
    sms: {
      senderID: 0,
      twoWaySMS: false,
      region: 'us-east-1'
    }
  },
  PN: {
    id: 'PN',
    cca3: 'PCN',
    callingCodes: [
      '64'
    ],
    title: 'Pitcairn Islands',
    awsRegion: 'us-west-1'
  },
  PE: {
    id: 'PE',
    cca3: 'PER',
    callingCodes: [
      '51'
    ],
    title: 'Peru',
    awsRegion: 'sa-east-1',
    sms: {
      senderID: 0,
      twoWaySMS: false,
      region: 'sa-east-1'
    }
  },
  PH: {
    id: 'PH',
    cca3: 'PHL',
    callingCodes: [
      '63'
    ],
    title: 'Philippines',
    awsRegion: 'ap-east-1',
    sms: {
      senderID: 2,
      twoWaySMS: true,
      region: 'ap-southeast-1'
    }
  },
  PW: {
    id: 'PW',
    cca3: 'PLW',
    callingCodes: [
      '680'
    ],
    title: 'Palau',
    awsRegion: 'ap-east-1',
    sms: {
      senderID: 0,
      twoWaySMS: false,
      region: 'ap-northeast-1'
    }
  },
  PG: {
    id: 'PG',
    cca3: 'PNG',
    callingCodes: [
      '675'
    ],
    title: 'Papua New Guinea',
    awsRegion: 'ap-southeast-2',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'ap-southeast-2'
    }
  },
  PL: {
    id: 'PL',
    cca3: 'POL',
    callingCodes: [
      '48'
    ],
    title: 'Poland',
    awsRegion: 'eu-central-1',
    sms: {
      senderID: 1,
      twoWaySMS: true,
      region: 'eu-central-1'
    }
  },
  PR: {
    id: 'PR',
    cca3: 'PRI',
    callingCodes: [
      '1787',
      '1939'
    ],
    title: 'Puerto Rico',
    awsRegion: 'us-east-1',
    sms: {
      senderID: 0,
      twoWaySMS: true,
      region: 'us-east-1'
    }
  },
  KP: {
    id: 'KP',
    cca3: 'PRK',
    callingCodes: [
      '850'
    ],
    title: 'North Korea',
    awsRegion: 'ap-northeast-2'
  },
  PT: {
    id: 'PT',
    cca3: 'PRT',
    callingCodes: [
      '351'
    ],
    title: 'Portugal',
    awsRegion: 'eu-west-3',
    sms: {
      senderID: 1,
      twoWaySMS: true,
      region: 'eu-west-3'
    }
  },
  PY: {
    id: 'PY',
    cca3: 'PRY',
    callingCodes: [
      '595'
    ],
    title: 'Paraguay',
    awsRegion: 'sa-east-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'sa-east-1'
    }
  },
  PS: {
    id: 'PS',
    cca3: 'PSE',
    callingCodes: [
      '970'
    ],
    title: 'Palestine',
    awsRegion: 'me-south-1',
    sms: {
      senderID: 0,
      twoWaySMS: false,
      region: 'me-south-1'
    }
  },
  PF: {
    id: 'PF',
    cca3: 'PYF',
    callingCodes: [
      '689'
    ],
    title: 'French Polynesia',
    awsRegion: 'us-west-1'
  },
  QA: {
    id: 'QA',
    cca3: 'QAT',
    callingCodes: [
      '974'
    ],
    title: 'Qatar',
    awsRegion: 'me-south-1',
    sms: {
      senderID: 2,
      twoWaySMS: false,
      region: 'me-south-1'
    }
  },
  RE: {
    id: 'RE',
    cca3: 'REU',
    callingCodes: [
      '262'
    ],
    title: 'Réunion',
    awsRegion: 'af-south-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'ap-south-1'
    }
  },
  RO: {
    id: 'RO',
    cca3: 'ROU',
    callingCodes: [
      '40'
    ],
    title: 'Romania',
    awsRegion: 'eu-south-1',
    sms: {
      senderID: 0,
      twoWaySMS: true,
      region: 'eu-central-1'
    }
  },
  RU: {
    id: 'RU',
    cca3: 'RUS',
    callingCodes: [
      '73',
      '74',
      '75',
      '78',
      '79'
    ],
    title: 'Russia',
    awsRegion: 'ap-northeast-2',
    sms: {
      senderID: 2,
      twoWaySMS: true,
      region: 'ap-northeast-1'
    }
  },
  RW: {
    id: 'RW',
    cca3: 'RWA',
    callingCodes: [
      '250'
    ],
    title: 'Rwanda',
    awsRegion: 'af-south-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'me-south-1'
    }
  },
  SA: {
    id: 'SA',
    cca3: 'SAU',
    callingCodes: [
      '966'
    ],
    title: 'Saudi Arabia',
    awsRegion: 'me-south-1',
    sms: {
      senderID: 2,
      twoWaySMS: false,
      region: 'me-south-1'
    }
  },
  SD: {
    id: 'SD',
    cca3: 'SDN',
    callingCodes: [
      '249'
    ],
    title: 'Sudan',
    awsRegion: 'me-south-1'
  },
  SN: {
    id: 'SN',
    cca3: 'SEN',
    callingCodes: [
      '221'
    ],
    title: 'Senegal',
    awsRegion: 'eu-south-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'eu-west-3'
    }
  },
  SG: {
    id: 'SG',
    cca3: 'SGP',
    callingCodes: [
      '65'
    ],
    title: 'Singapore',
    awsRegion: 'ap-southeast-1',
    sms: {
      senderID: 1,
      twoWaySMS: true,
      region: 'ap-southeast-1'
    }
  },
  GS: {
    id: 'GS',
    cca3: 'SGS',
    callingCodes: [
      '500'
    ],
    title: 'South Georgia',
    awsRegion: 'sa-east-1'
  },
  SJ: {
    id: 'SJ',
    cca3: 'SJM',
    callingCodes: [
      '4779'
    ],
    title: 'Svalbard and Jan Mayen',
    awsRegion: 'eu-north-1'
  },
  SB: {
    id: 'SB',
    cca3: 'SLB',
    callingCodes: [
      '677'
    ],
    title: 'Solomon Islands',
    awsRegion: 'ap-southeast-2',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'ap-southeast-2'
    }
  },
  SL: {
    id: 'SL',
    cca3: 'SLE',
    callingCodes: [
      '232'
    ],
    title: 'Sierra Leone',
    awsRegion: 'eu-south-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'eu-west-3'
    }
  },
  SV: {
    id: 'SV',
    cca3: 'SLV',
    callingCodes: [
      '503'
    ],
    title: 'El Salvador',
    awsRegion: 'us-east-2',
    sms: {
      senderID: 0,
      twoWaySMS: false,
      region: 'us-east-2'
    }
  },
  SM: {
    id: 'SM',
    cca3: 'SMR',
    callingCodes: [
      '378'
    ],
    title: 'San Marino',
    awsRegion: 'eu-south-1'
  },
  SO: {
    id: 'SO',
    cca3: 'SOM',
    callingCodes: [
      '252'
    ],
    title: 'Somalia',
    awsRegion: 'me-south-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'me-south-1'
    }
  },
  PM: {
    id: 'PM',
    cca3: 'SPM',
    callingCodes: [
      '508'
    ],
    title: 'Saint Pierre and Miquelon',
    awsRegion: 'ca-central-1'
  },
  RS: {
    id: 'RS',
    cca3: 'SRB',
    callingCodes: [
      '381'
    ],
    title: 'Serbia',
    awsRegion: 'eu-south-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'eu-central-1'
    }
  },
  SS: {
    id: 'SS',
    cca3: 'SSD',
    callingCodes: [
      '211'
    ],
    title: 'South Sudan',
    awsRegion: 'me-south-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'me-south-1'
    }
  },
  ST: {
    id: 'ST',
    cca3: 'STP',
    callingCodes: [
      '239'
    ],
    title: 'São Tomé and Príncipe',
    awsRegion: 'af-south-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'eu-west-3'
    }
  },
  SR: {
    id: 'SR',
    cca3: 'SUR',
    callingCodes: [
      '597'
    ],
    title: 'Suriname',
    awsRegion: 'sa-east-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'sa-east-1'
    }
  },
  SK: {
    id: 'SK',
    cca3: 'SVK',
    callingCodes: [
      '421'
    ],
    title: 'Slovakia',
    awsRegion: 'eu-central-1',
    sms: {
      senderID: 1,
      twoWaySMS: true,
      region: 'eu-central-1'
    }
  },
  SI: {
    id: 'SI',
    cca3: 'SVN',
    callingCodes: [
      '386'
    ],
    title: 'Slovenia',
    awsRegion: 'eu-south-1',
    sms: {
      senderID: 1,
      twoWaySMS: true,
      region: 'eu-central-1'
    }
  },
  SE: {
    id: 'SE',
    cca3: 'SWE',
    callingCodes: [
      '46'
    ],
    title: 'Sweden',
    awsRegion: 'eu-north-1',
    sms: {
      senderID: 1,
      twoWaySMS: true,
      region: 'eu-north-1'
    }
  },
  SZ: {
    id: 'SZ',
    cca3: 'SWZ',
    callingCodes: [
      '268'
    ],
    title: 'Eswatini',
    awsRegion: 'af-south-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'me-south-1'
    }
  },
  SX: {
    id: 'SX',
    cca3: 'SXM',
    callingCodes: [
      '1721'
    ],
    title: 'Sint Maarten',
    awsRegion: 'us-east-1'
  },
  SC: {
    id: 'SC',
    cca3: 'SYC',
    callingCodes: [
      '248'
    ],
    title: 'Seychelles',
    awsRegion: 'ap-south-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'ap-south-1'
    }
  },
  SY: {
    id: 'SY',
    cca3: 'SYR',
    callingCodes: [
      '963'
    ],
    title: 'Syria',
    awsRegion: 'me-south-1'
  },
  TC: {
    id: 'TC',
    cca3: 'TCA',
    callingCodes: [
      '1649'
    ],
    title: 'Turks and Caicos Islands',
    awsRegion: 'us-east-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'us-east-1'
    }
  },
  TD: {
    id: 'TD',
    cca3: 'TCD',
    callingCodes: [
      '235'
    ],
    title: 'Chad',
    awsRegion: 'me-south-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'me-south-1'
    }
  },
  TG: {
    id: 'TG',
    cca3: 'TGO',
    callingCodes: [
      '228'
    ],
    title: 'Togo',
    awsRegion: 'eu-south-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'eu-west-3'
    }
  },
  TH: {
    id: 'TH',
    cca3: 'THA',
    callingCodes: [
      '66'
    ],
    title: 'Thailand',
    awsRegion: 'ap-southeast-1',
    sms: {
      senderID: 2,
      twoWaySMS: true,
      region: 'ap-southeast-1'
    }
  },
  TJ: {
    id: 'TJ',
    cca3: 'TJK',
    callingCodes: [
      '992'
    ],
    title: 'Tajikistan',
    awsRegion: 'ap-south-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'ap-south-1'
    }
  },
  TK: {
    id: 'TK',
    cca3: 'TKL',
    callingCodes: [
      '690'
    ],
    title: 'Tokelau',
    awsRegion: 'ap-southeast-2'
  },
  TM: {
    id: 'TM',
    cca3: 'TKM',
    callingCodes: [
      '993'
    ],
    title: 'Turkmenistan',
    awsRegion: 'me-south-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'me-south-1'
    }
  },
  TL: {
    id: 'TL',
    cca3: 'TLS',
    callingCodes: [
      '670'
    ],
    title: 'Timor-Leste',
    awsRegion: 'ap-southeast-1',
    sms: {
      senderID: 0,
      twoWaySMS: false,
      region: 'ap-southeast-1'
    }
  },
  TO: {
    id: 'TO',
    cca3: 'TON',
    callingCodes: [
      '676'
    ],
    title: 'Tonga',
    awsRegion: 'ap-southeast-2',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'ap-southeast-2'
    }
  },
  TT: {
    id: 'TT',
    cca3: 'TTO',
    callingCodes: [
      '1868'
    ],
    title: 'Trinidad and Tobago',
    awsRegion: 'us-east-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'us-east-1'
    }
  },
  TN: {
    id: 'TN',
    cca3: 'TUN',
    callingCodes: [
      '216'
    ],
    title: 'Tunisia',
    awsRegion: 'eu-south-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'eu-west-3'
    }
  },
  TR: {
    id: 'TR',
    cca3: 'TUR',
    callingCodes: [
      '90'
    ],
    title: 'Turkey',
    awsRegion: 'me-south-1',
    sms: {
      senderID: 2,
      twoWaySMS: true,
      region: 'me-south-1'
    }
  },
  TV: {
    id: 'TV',
    cca3: 'TUV',
    callingCodes: [
      '688'
    ],
    title: 'Tuvalu',
    awsRegion: 'ap-southeast-2'
  },
  TW: {
    id: 'TW',
    cca3: 'TWN',
    callingCodes: [
      '886'
    ],
    title: 'Taiwan',
    awsRegion: 'ap-east-1',
    sms: {
      senderID: 0,
      twoWaySMS: true,
      region: 'ap-northeast-1'
    }
  },
  TZ: {
    id: 'TZ',
    cca3: 'TZA',
    callingCodes: [
      '255'
    ],
    title: 'Tanzania',
    awsRegion: 'af-south-1',
    sms: {
      senderID: 0,
      twoWaySMS: false,
      region: 'me-south-1'
    }
  },
  UG: {
    id: 'UG',
    cca3: 'UGA',
    callingCodes: [
      '256'
    ],
    title: 'Uganda',
    awsRegion: 'me-south-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'me-south-1'
    }
  },
  UA: {
    id: 'UA',
    cca3: 'UKR',
    callingCodes: [
      '380'
    ],
    title: 'Ukraine',
    awsRegion: 'eu-north-1',
    sms: {
      senderID: 1,
      twoWaySMS: true,
      region: 'eu-north-1'
    }
  },
  UM: {
    id: 'UM',
    cca3: 'UMI',
    callingCodes: [
      '268'
    ],
    title: 'United States Minor Outlying Islands',
    awsRegion: 'ap-northeast-1'
  },
  UY: {
    id: 'UY',
    cca3: 'URY',
    callingCodes: [
      '598'
    ],
    title: 'Uruguay',
    awsRegion: 'sa-east-1',
    sms: {
      senderID: 0,
      twoWaySMS: false,
      region: 'sa-east-1'
    }
  },
  US: {
    id: 'US',
    cca3: 'USA',
    callingCodes: [
      '1201',
      '1202',
      '1203',
      '1205',
      '1206',
      '1207',
      '1208',
      '1209',
      '1210',
      '1212',
      '1213',
      '1214',
      '1215',
      '1216',
      '1217',
      '1218',
      '1219',
      '1220',
      '1224',
      '1225',
      '1227',
      '1228',
      '1229',
      '1231',
      '1234',
      '1239',
      '1240',
      '1248',
      '1251',
      '1252',
      '1253',
      '1254',
      '1256',
      '1260',
      '1262',
      '1267',
      '1269',
      '1270',
      '1272',
      '1274',
      '1276',
      '1281',
      '1283',
      '1301',
      '1302',
      '1303',
      '1304',
      '1305',
      '1307',
      '1308',
      '1309',
      '1310',
      '1312',
      '1313',
      '1314',
      '1315',
      '1316',
      '1317',
      '1318',
      '1319',
      '1320',
      '1321',
      '1323',
      '1325',
      '1327',
      '1330',
      '1331',
      '1334',
      '1336',
      '1337',
      '1339',
      '1346',
      '1347',
      '1351',
      '1352',
      '1360',
      '1361',
      '1364',
      '1380',
      '1385',
      '1386',
      '1401',
      '1402',
      '1404',
      '1405',
      '1406',
      '1407',
      '1408',
      '1409',
      '1410',
      '1412',
      '1413',
      '1414',
      '1415',
      '1417',
      '1419',
      '1423',
      '1424',
      '1425',
      '1430',
      '1432',
      '1434',
      '1435',
      '1440',
      '1442',
      '1443',
      '1447',
      '1458',
      '1463',
      '1464',
      '1469',
      '1470',
      '1475',
      '1478',
      '1479',
      '1480',
      '1484',
      '1501',
      '1502',
      '1503',
      '1504',
      '1505',
      '1507',
      '1508',
      '1509',
      '1510',
      '1512',
      '1513',
      '1515',
      '1516',
      '1517',
      '1518',
      '1520',
      '1530',
      '1531',
      '1534',
      '1539',
      '1540',
      '1541',
      '1551',
      '1559',
      '1561',
      '1562',
      '1563',
      '1564',
      '1567',
      '1570',
      '1571',
      '1573',
      '1574',
      '1575',
      '1580',
      '1585',
      '1586',
      '1601',
      '1602',
      '1603',
      '1605',
      '1606',
      '1607',
      '1608',
      '1609',
      '1610',
      '1612',
      '1614',
      '1615',
      '1616',
      '1617',
      '1618',
      '1619',
      '1620',
      '1623',
      '1626',
      '1628',
      '1629',
      '1630',
      '1631',
      '1636',
      '1641',
      '1646',
      '1650',
      '1651',
      '1657',
      '1660',
      '1661',
      '1662',
      '1667',
      '1669',
      '1678',
      '1681',
      '1682',
      '1701',
      '1702',
      '1703',
      '1704',
      '1706',
      '1707',
      '1708',
      '1712',
      '1713',
      '1714',
      '1715',
      '1716',
      '1717',
      '1718',
      '1719',
      '1720',
      '1724',
      '1725',
      '1727',
      '1730',
      '1731',
      '1732',
      '1734',
      '1737',
      '1740',
      '1743',
      '1747',
      '1754',
      '1757',
      '1760',
      '1762',
      '1763',
      '1765',
      '1769',
      '1770',
      '1772',
      '1773',
      '1774',
      '1775',
      '1779',
      '1781',
      '1785',
      '1786',
      '1801',
      '1802',
      '1803',
      '1804',
      '1805',
      '1806',
      '1808',
      '1810',
      '1812',
      '1813',
      '1814',
      '1815',
      '1816',
      '1817',
      '1818',
      '1828',
      '1830',
      '1831',
      '1832',
      '1843',
      '1845',
      '1847',
      '1848',
      '1850',
      '1854',
      '1856',
      '1857',
      '1858',
      '1859',
      '1860',
      '1862',
      '1863',
      '1864',
      '1865',
      '1870',
      '1872',
      '1878',
      '1901',
      '1903',
      '1904',
      '1906',
      '1907',
      '1908',
      '1909',
      '1910',
      '1912',
      '1913',
      '1914',
      '1915',
      '1916',
      '1917',
      '1918',
      '1919',
      '1920',
      '1925',
      '1928',
      '1929',
      '1930',
      '1931',
      '1934',
      '1936',
      '1937',
      '1938',
      '1940',
      '1941',
      '1947',
      '1949',
      '1951',
      '1952',
      '1954',
      '1956',
      '1959',
      '1970',
      '1971',
      '1972',
      '1973',
      '1975',
      '1978',
      '1979',
      '1980',
      '1984',
      '1985',
      '1989'
    ],
    title: 'United States',
    awsRegion: 'us-east-2',
    sms: {
      senderID: 0,
      twoWaySMS: true,
      region: 'us-east-2'
    }
  },
  UZ: {
    id: 'UZ',
    cca3: 'UZB',
    callingCodes: [
      '998'
    ],
    title: 'Uzbekistan',
    awsRegion: 'me-south-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'me-south-1'
    }
  },
  VA: {
    id: 'VA',
    cca3: 'VAT',
    callingCodes: [
      '3906698',
      '379'
    ],
    title: 'Vatican City',
    awsRegion: 'eu-south-1'
  },
  VC: {
    id: 'VC',
    cca3: 'VCT',
    callingCodes: [
      '1784'
    ],
    title: 'Saint Vincent and the Grenadines',
    awsRegion: 'us-east-1',
    sms: {
      senderID: 0,
      twoWaySMS: false,
      region: 'us-east-1'
    }
  },
  VE: {
    id: 'VE',
    cca3: 'VEN',
    callingCodes: [
      '58'
    ],
    title: 'Venezuela',
    awsRegion: 'us-east-1',
    sms: {
      senderID: 0,
      twoWaySMS: false,
      region: 'us-east-1'
    }
  },
  VG: {
    id: 'VG',
    cca3: 'VGB',
    callingCodes: [
      '1284'
    ],
    title: 'British Virgin Islands',
    awsRegion: 'us-east-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'us-east-1'
    }
  },
  VI: {
    id: 'VI',
    cca3: 'VIR',
    callingCodes: [
      '1340'
    ],
    title: 'United States Virgin Islands',
    awsRegion: 'us-east-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'us-east-1'
    }
  },
  VN: {
    id: 'VN',
    cca3: 'VNM',
    callingCodes: [
      '84'
    ],
    title: 'Vietnam',
    awsRegion: 'ap-east-1',
    sms: {
      senderID: 2,
      twoWaySMS: false,
      region: 'ap-southeast-1'
    }
  },
  VU: {
    id: 'VU',
    cca3: 'VUT',
    callingCodes: [
      '678'
    ],
    title: 'Vanuatu',
    awsRegion: 'ap-southeast-2',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'ap-southeast-2'
    }
  },
  WF: {
    id: 'WF',
    cca3: 'WLF',
    callingCodes: [
      '681'
    ],
    title: 'Wallis and Futuna',
    awsRegion: 'ap-southeast-2'
  },
  WS: {
    id: 'WS',
    cca3: 'WSM',
    callingCodes: [
      '685'
    ],
    title: 'Samoa',
    awsRegion: 'ap-southeast-2',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'ap-southeast-2'
    }
  },
  YE: {
    id: 'YE',
    cca3: 'YEM',
    callingCodes: [
      '967'
    ],
    title: 'Yemen',
    awsRegion: 'me-south-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'me-south-1'
    }
  },
  ZA: {
    id: 'ZA',
    cca3: 'ZAF',
    callingCodes: [
      '27'
    ],
    title: 'South Africa',
    awsRegion: 'af-south-1',
    sms: {
      senderID: 0,
      twoWaySMS: true,
      region: 'me-south-1'
    }
  },
  ZM: {
    id: 'ZM',
    cca3: 'ZMB',
    callingCodes: [
      '260'
    ],
    title: 'Zambia',
    awsRegion: 'af-south-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'me-south-1'
    }
  },
  ZW: {
    id: 'ZW',
    cca3: 'ZWE',
    callingCodes: [
      '263'
    ],
    title: 'Zimbabwe',
    awsRegion: 'af-south-1',
    sms: {
      senderID: 1,
      twoWaySMS: false,
      region: 'me-south-1'
    }
  }
}
