// Generated by "npm run generate_info" in tradle/aws-utils repository
import { SenderID, Partition } from './types'
import { Country, Region, Coordinates } from './types'

const coord = (latitude: number, longitude: number): Coordinates => ({
  latitude,
  longitude
})

/**
 * Information about the world's countries, including aws information
 */
export const getCountries = () => [
  {
    id: 'AW',
    cca3: 'ABW',
    callingCodes: [
      '297'
    ],
    title: 'Aruba',
    loc: coord(12.5, -69.97),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'AF',
    cca3: 'AFG',
    callingCodes: [
      '93'
    ],
    title: 'Afghanistan',
    loc: coord(33, 65),
    sms: {
      senderID: SenderID.Unavailable,
      twoWaySMS: false
    }
  },
  {
    id: 'AO',
    cca3: 'AGO',
    callingCodes: [
      '244'
    ],
    title: 'Angola',
    loc: coord(-12.5, 18.5),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'AI',
    cca3: 'AIA',
    callingCodes: [
      '1264'
    ],
    title: 'Anguilla',
    loc: coord(18.25, -63.17),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'AX',
    cca3: 'ALA',
    callingCodes: [
      '35818'
    ],
    title: 'Åland Islands',
    loc: coord(60.12, 19.9)
  },
  {
    id: 'AL',
    cca3: 'ALB',
    callingCodes: [
      '355'
    ],
    title: 'Albania',
    loc: coord(41, 20),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'AD',
    cca3: 'AND',
    callingCodes: [
      '376'
    ],
    title: 'Andorra',
    loc: coord(42.5, 1.5),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'AE',
    cca3: 'ARE',
    callingCodes: [
      '971'
    ],
    title: 'United Arab Emirates',
    loc: coord(24, 54),
    sms: {
      senderID: SenderID.PreRequisitesRequired,
      twoWaySMS: false
    }
  },
  {
    id: 'AR',
    cca3: 'ARG',
    callingCodes: [
      '54'
    ],
    title: 'Argentina',
    loc: coord(-34, -64),
    sms: {
      senderID: SenderID.Unavailable,
      twoWaySMS: false
    }
  },
  {
    id: 'AM',
    cca3: 'ARM',
    callingCodes: [
      '374'
    ],
    title: 'Armenia',
    loc: coord(40, 45),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'AS',
    cca3: 'ASM',
    callingCodes: [
      '1684'
    ],
    title: 'American Samoa',
    loc: coord(-14.33, -170)
  },
  {
    id: 'AQ',
    cca3: 'ATA',
    callingCodes: [],
    title: 'Antarctica',
    loc: coord(-90, 0)
  },
  {
    id: 'TF',
    cca3: 'ATF',
    callingCodes: [
      '262'
    ],
    title: 'French Southern and Antarctic Lands',
    loc: coord(-49.25, 69.17)
  },
  {
    id: 'AG',
    cca3: 'ATG',
    callingCodes: [
      '1268'
    ],
    title: 'Antigua and Barbuda',
    loc: coord(17.05, -61.8),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'AU',
    cca3: 'AUS',
    callingCodes: [
      '61'
    ],
    title: 'Australia',
    loc: coord(-27, 133),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: true
    }
  },
  {
    id: 'AT',
    cca3: 'AUT',
    callingCodes: [
      '43'
    ],
    title: 'Austria',
    loc: coord(47.33, 13.33),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: true
    }
  },
  {
    id: 'AZ',
    cca3: 'AZE',
    callingCodes: [
      '994'
    ],
    title: 'Azerbaijan',
    loc: coord(40.5, 47.5),
    sms: {
      senderID: SenderID.Unavailable,
      twoWaySMS: false
    }
  },
  {
    id: 'BI',
    cca3: 'BDI',
    callingCodes: [
      '257'
    ],
    title: 'Burundi',
    loc: coord(-3.5, 30),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'BE',
    cca3: 'BEL',
    callingCodes: [
      '32'
    ],
    title: 'Belgium',
    loc: coord(50.83, 4),
    sms: {
      senderID: SenderID.Unavailable,
      twoWaySMS: true
    }
  },
  {
    id: 'BJ',
    cca3: 'BEN',
    callingCodes: [
      '229'
    ],
    title: 'Benin',
    loc: coord(9.5, 2.25),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'BF',
    cca3: 'BFA',
    callingCodes: [
      '226'
    ],
    title: 'Burkina Faso',
    loc: coord(13, -2),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'BD',
    cca3: 'BGD',
    callingCodes: [
      '880'
    ],
    title: 'Bangladesh',
    loc: coord(24, 90),
    sms: {
      senderID: SenderID.Unavailable,
      twoWaySMS: false
    }
  },
  {
    id: 'BG',
    cca3: 'BGR',
    callingCodes: [
      '359'
    ],
    title: 'Bulgaria',
    loc: coord(43, 25),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'BH',
    cca3: 'BHR',
    callingCodes: [
      '973'
    ],
    title: 'Bahrain',
    loc: coord(26, 50.55),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: true
    }
  },
  {
    id: 'BS',
    cca3: 'BHS',
    callingCodes: [
      '1242'
    ],
    title: 'Bahamas',
    loc: coord(24.25, -76),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'BA',
    cca3: 'BIH',
    callingCodes: [
      '387'
    ],
    title: 'Bosnia and Herzegovina',
    loc: coord(44, 18),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'BL',
    cca3: 'BLM',
    callingCodes: [
      '590'
    ],
    title: 'Saint Barthélemy',
    loc: coord(18.5, -63.42)
  },
  {
    id: 'SH',
    cca3: 'SHN',
    callingCodes: [
      '290',
      '247'
    ],
    title: 'Saint Helena, Ascension and Tristan da Cunha',
    loc: coord(-15.95, -5.72)
  },
  {
    id: 'BY',
    cca3: 'BLR',
    callingCodes: [
      '375'
    ],
    title: 'Belarus',
    loc: coord(53, 28),
    sms: {
      senderID: SenderID.PreRequisitesRequired,
      twoWaySMS: false
    }
  },
  {
    id: 'BZ',
    cca3: 'BLZ',
    callingCodes: [
      '501'
    ],
    title: 'Belize',
    loc: coord(17.25, -88.75),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'BM',
    cca3: 'BMU',
    callingCodes: [
      '1441'
    ],
    title: 'Bermuda',
    loc: coord(32.33, -64.75),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'BO',
    cca3: 'BOL',
    callingCodes: [
      '591'
    ],
    title: 'Bolivia',
    loc: coord(-17, -65),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'BQ',
    cca3: 'BES',
    callingCodes: [
      '599'
    ],
    title: 'Caribbean Netherlands',
    loc: coord(12.18, -68.25)
  },
  {
    id: 'BR',
    cca3: 'BRA',
    callingCodes: [
      '55'
    ],
    title: 'Brazil',
    loc: coord(-10, -55),
    sms: {
      senderID: SenderID.Unavailable,
      twoWaySMS: true
    }
  },
  {
    id: 'BB',
    cca3: 'BRB',
    callingCodes: [
      '1246'
    ],
    title: 'Barbados',
    loc: coord(13.17, -59.53),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'BN',
    cca3: 'BRN',
    callingCodes: [
      '673'
    ],
    title: 'Brunei',
    loc: coord(4.5, 114.67),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'BT',
    cca3: 'BTN',
    callingCodes: [
      '975'
    ],
    title: 'Bhutan',
    loc: coord(27.5, 90.5),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'BV',
    cca3: 'BVT',
    callingCodes: [
      '47'
    ],
    title: 'Bouvet Island',
    loc: coord(-54.43, 3.4)
  },
  {
    id: 'BW',
    cca3: 'BWA',
    callingCodes: [
      '267'
    ],
    title: 'Botswana',
    loc: coord(-22, 24),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'CF',
    cca3: 'CAF',
    callingCodes: [
      '236'
    ],
    title: 'Central African Republic',
    loc: coord(7, 21),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'CA',
    cca3: 'CAN',
    callingCodes: [
      '1'
    ],
    title: 'Canada',
    loc: coord(60, -95),
    sms: {
      senderID: SenderID.Unavailable,
      twoWaySMS: true
    }
  },
  {
    id: 'CC',
    cca3: 'CCK',
    callingCodes: [
      '61'
    ],
    title: 'Cocos (Keeling) Islands',
    loc: coord(-12.5, 96.83)
  },
  {
    id: 'CH',
    cca3: 'CHE',
    callingCodes: [
      '41'
    ],
    title: 'Switzerland',
    loc: coord(47, 8),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: true
    }
  },
  {
    id: 'CL',
    cca3: 'CHL',
    callingCodes: [
      '56'
    ],
    title: 'Chile',
    loc: coord(-30, -71),
    sms: {
      senderID: SenderID.Unavailable,
      twoWaySMS: true
    }
  },
  {
    id: 'CN',
    cca3: 'CHN',
    callingCodes: [
      '86'
    ],
    title: 'China',
    loc: coord(35, 105),
    sms: {
      senderID: SenderID.Unavailable,
      twoWaySMS: false
    }
  },
  {
    id: 'CI',
    cca3: 'CIV',
    callingCodes: [
      '225'
    ],
    title: 'Ivory Coast',
    loc: coord(8, -5),
    sms: {
      senderID: SenderID.Unavailable,
      twoWaySMS: false
    }
  },
  {
    id: 'CM',
    cca3: 'CMR',
    callingCodes: [
      '237'
    ],
    title: 'Cameroon',
    loc: coord(6, 12),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'CD',
    cca3: 'COD',
    callingCodes: [
      '243'
    ],
    title: 'DR Congo',
    loc: coord(0, 25),
    sms: {
      senderID: SenderID.Unavailable,
      twoWaySMS: false
    }
  },
  {
    id: 'CG',
    cca3: 'COG',
    callingCodes: [
      '242'
    ],
    title: 'Republic of the Congo',
    loc: coord(-1, 15),
    sms: {
      senderID: SenderID.Unavailable,
      twoWaySMS: false
    }
  },
  {
    id: 'CK',
    cca3: 'COK',
    callingCodes: [
      '682'
    ],
    title: 'Cook Islands',
    loc: coord(-21.23, -159.77),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'CO',
    cca3: 'COL',
    callingCodes: [
      '57'
    ],
    title: 'Colombia',
    loc: coord(4, -72),
    sms: {
      senderID: SenderID.Unavailable,
      twoWaySMS: false
    }
  },
  {
    id: 'KM',
    cca3: 'COM',
    callingCodes: [
      '269'
    ],
    title: 'Comoros',
    loc: coord(-12.17, 44.25),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'CV',
    cca3: 'CPV',
    callingCodes: [
      '238'
    ],
    title: 'Cape Verde',
    loc: coord(16, -24),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'CR',
    cca3: 'CRI',
    callingCodes: [
      '506'
    ],
    title: 'Costa Rica',
    loc: coord(10, -84),
    sms: {
      senderID: SenderID.Unavailable,
      twoWaySMS: false
    }
  },
  {
    id: 'CU',
    cca3: 'CUB',
    callingCodes: [
      '53'
    ],
    title: 'Cuba',
    loc: coord(21.5, -80)
  },
  {
    id: 'CW',
    cca3: 'CUW',
    callingCodes: [
      '599'
    ],
    title: 'Curaçao',
    loc: coord(12.12, -68.93)
  },
  {
    id: 'CX',
    cca3: 'CXR',
    callingCodes: [
      '61'
    ],
    title: 'Christmas Island',
    loc: coord(-10.5, 105.67)
  },
  {
    id: 'KY',
    cca3: 'CYM',
    callingCodes: [
      '1345'
    ],
    title: 'Cayman Islands',
    loc: coord(19.5, -80.5),
    sms: {
      senderID: SenderID.Unavailable,
      twoWaySMS: false
    }
  },
  {
    id: 'CY',
    cca3: 'CYP',
    callingCodes: [
      '357'
    ],
    title: 'Cyprus',
    loc: coord(35, 33),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'CZ',
    cca3: 'CZE',
    callingCodes: [
      '420'
    ],
    title: 'Czechia',
    loc: coord(49.75, 15.5),
    sms: {
      senderID: SenderID.Unavailable,
      twoWaySMS: true
    }
  },
  {
    id: 'DE',
    cca3: 'DEU',
    callingCodes: [
      '49'
    ],
    title: 'Germany',
    loc: coord(51, 9),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: true
    }
  },
  {
    id: 'DJ',
    cca3: 'DJI',
    callingCodes: [
      '253'
    ],
    title: 'Djibouti',
    loc: coord(11.5, 43),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'DM',
    cca3: 'DMA',
    callingCodes: [
      '1767'
    ],
    title: 'Dominica',
    loc: coord(15.42, -61.33),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'DK',
    cca3: 'DNK',
    callingCodes: [
      '45'
    ],
    title: 'Denmark',
    loc: coord(56, 10),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: true
    }
  },
  {
    id: 'DO',
    cca3: 'DOM',
    callingCodes: [
      '1809',
      '1829',
      '1849'
    ],
    title: 'Dominican Republic',
    loc: coord(19, -70.67),
    sms: {
      senderID: SenderID.Unavailable,
      twoWaySMS: false
    }
  },
  {
    id: 'DZ',
    cca3: 'DZA',
    callingCodes: [
      '213'
    ],
    title: 'Algeria',
    loc: coord(28, 3),
    sms: {
      senderID: SenderID.Unavailable,
      twoWaySMS: false
    }
  },
  {
    id: 'EC',
    cca3: 'ECU',
    callingCodes: [
      '593'
    ],
    title: 'Ecuador',
    loc: coord(-2, -77.5),
    sms: {
      senderID: SenderID.Unavailable,
      twoWaySMS: false
    }
  },
  {
    id: 'EG',
    cca3: 'EGY',
    callingCodes: [
      '20'
    ],
    title: 'Egypt',
    loc: coord(27, 30),
    sms: {
      senderID: SenderID.PreRequisitesRequired,
      twoWaySMS: false
    }
  },
  {
    id: 'ER',
    cca3: 'ERI',
    callingCodes: [
      '291'
    ],
    title: 'Eritrea',
    loc: coord(15, 39)
  },
  {
    id: 'EH',
    cca3: 'ESH',
    callingCodes: [
      '2125288',
      '2125289'
    ],
    title: 'Western Sahara',
    loc: coord(24.5, -13)
  },
  {
    id: 'ES',
    cca3: 'ESP',
    callingCodes: [
      '34'
    ],
    title: 'Spain',
    loc: coord(40, -4),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: true
    }
  },
  {
    id: 'EE',
    cca3: 'EST',
    callingCodes: [
      '372'
    ],
    title: 'Estonia',
    loc: coord(59, 26),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: true
    }
  },
  {
    id: 'ET',
    cca3: 'ETH',
    callingCodes: [
      '251'
    ],
    title: 'Ethiopia',
    loc: coord(8, 38),
    sms: {
      senderID: SenderID.Unavailable,
      twoWaySMS: false
    }
  },
  {
    id: 'FI',
    cca3: 'FIN',
    callingCodes: [
      '358'
    ],
    title: 'Finland',
    loc: coord(64, 26),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: true
    }
  },
  {
    id: 'FJ',
    cca3: 'FJI',
    callingCodes: [
      '679'
    ],
    title: 'Fiji',
    loc: coord(-18, 175),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'FK',
    cca3: 'FLK',
    callingCodes: [
      '500'
    ],
    title: 'Falkland Islands',
    loc: coord(-51.75, -59)
  },
  {
    id: 'FR',
    cca3: 'FRA',
    callingCodes: [
      '33'
    ],
    title: 'France',
    loc: coord(46, 2),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: true
    }
  },
  {
    id: 'FO',
    cca3: 'FRO',
    callingCodes: [
      '298'
    ],
    title: 'Faroe Islands',
    loc: coord(62, -7),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'FM',
    cca3: 'FSM',
    callingCodes: [
      '691'
    ],
    title: 'Micronesia',
    loc: coord(6.92, 158.25)
  },
  {
    id: 'GA',
    cca3: 'GAB',
    callingCodes: [
      '241'
    ],
    title: 'Gabon',
    loc: coord(-1, 11.75),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'GB',
    cca3: 'GBR',
    callingCodes: [
      '44'
    ],
    title: 'United Kingdom',
    loc: coord(54, -2),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: true
    }
  },
  {
    id: 'GE',
    cca3: 'GEO',
    callingCodes: [
      '995'
    ],
    title: 'Georgia',
    loc: coord(42, 43.5),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'GG',
    cca3: 'GGY',
    callingCodes: [
      '44'
    ],
    title: 'Guernsey',
    loc: coord(49.47, -2.58)
  },
  {
    id: 'GH',
    cca3: 'GHA',
    callingCodes: [
      '233'
    ],
    title: 'Ghana',
    loc: coord(8, -2),
    sms: {
      senderID: SenderID.Unavailable,
      twoWaySMS: false
    }
  },
  {
    id: 'GI',
    cca3: 'GIB',
    callingCodes: [
      '350'
    ],
    title: 'Gibraltar',
    loc: coord(36.13, -5.35),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'GN',
    cca3: 'GIN',
    callingCodes: [
      '224'
    ],
    title: 'Guinea',
    loc: coord(11, -10),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'GP',
    cca3: 'GLP',
    callingCodes: [
      '590'
    ],
    title: 'Guadeloupe',
    loc: coord(16.25, -61.58),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'GM',
    cca3: 'GMB',
    callingCodes: [
      '220'
    ],
    title: 'Gambia',
    loc: coord(13.47, -16.57),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'GW',
    cca3: 'GNB',
    callingCodes: [
      '245'
    ],
    title: 'Guinea-Bissau',
    loc: coord(12, -15),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'GQ',
    cca3: 'GNQ',
    callingCodes: [
      '240'
    ],
    title: 'Equatorial Guinea',
    loc: coord(2, 10),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'GR',
    cca3: 'GRC',
    callingCodes: [
      '30'
    ],
    title: 'Greece',
    loc: coord(39, 22),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'GD',
    cca3: 'GRD',
    callingCodes: [
      '1473'
    ],
    title: 'Grenada',
    loc: coord(12.12, -61.67),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'GL',
    cca3: 'GRL',
    callingCodes: [
      '299'
    ],
    title: 'Greenland',
    loc: coord(72, -40),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'GT',
    cca3: 'GTM',
    callingCodes: [
      '502'
    ],
    title: 'Guatemala',
    loc: coord(15.5, -90.25),
    sms: {
      senderID: SenderID.Unavailable,
      twoWaySMS: true
    }
  },
  {
    id: 'GF',
    cca3: 'GUF',
    callingCodes: [
      '594'
    ],
    title: 'French Guiana',
    loc: coord(4, -53),
    sms: {
      senderID: SenderID.Unavailable,
      twoWaySMS: false
    }
  },
  {
    id: 'GU',
    cca3: 'GUM',
    callingCodes: [
      '1671'
    ],
    title: 'Guam',
    loc: coord(13.47, 144.78),
    sms: {
      senderID: SenderID.Unavailable,
      twoWaySMS: false
    }
  },
  {
    id: 'GY',
    cca3: 'GUY',
    callingCodes: [
      '592'
    ],
    title: 'Guyana',
    loc: coord(5, -59),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'HK',
    cca3: 'HKG',
    callingCodes: [
      '852'
    ],
    title: 'Hong Kong',
    loc: coord(22.27, 114.19),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: true
    }
  },
  {
    id: 'HM',
    cca3: 'HMD',
    callingCodes: [
      ''
    ],
    title: 'Heard Island and McDonald Islands',
    loc: coord(-53.1, 72.52)
  },
  {
    id: 'HN',
    cca3: 'HND',
    callingCodes: [
      '504'
    ],
    title: 'Honduras',
    loc: coord(15, -86.5),
    sms: {
      senderID: SenderID.Unavailable,
      twoWaySMS: true
    }
  },
  {
    id: 'HR',
    cca3: 'HRV',
    callingCodes: [
      '385'
    ],
    title: 'Croatia',
    loc: coord(45.17, 15.5),
    sms: {
      senderID: SenderID.Unavailable,
      twoWaySMS: true
    }
  },
  {
    id: 'HT',
    cca3: 'HTI',
    callingCodes: [
      '509'
    ],
    title: 'Haiti',
    loc: coord(19, -72.42),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'HU',
    cca3: 'HUN',
    callingCodes: [
      '36'
    ],
    title: 'Hungary',
    loc: coord(47, 20),
    sms: {
      senderID: SenderID.Unavailable,
      twoWaySMS: true
    }
  },
  {
    id: 'ID',
    cca3: 'IDN',
    callingCodes: [
      '62'
    ],
    title: 'Indonesia',
    loc: coord(-5, 120),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'IM',
    cca3: 'IMN',
    callingCodes: [
      '44'
    ],
    title: 'Isle of Man',
    loc: coord(54.25, -4.5)
  },
  {
    id: 'IN',
    cca3: 'IND',
    callingCodes: [
      '91'
    ],
    title: 'India',
    loc: coord(20, 77),
    sms: {
      senderID: SenderID.PreRequisitesRequired,
      twoWaySMS: true
    }
  },
  {
    id: 'IO',
    cca3: 'IOT',
    callingCodes: [
      '246'
    ],
    title: 'British Indian Ocean Territory',
    loc: coord(-6, 71.5)
  },
  {
    id: 'IE',
    cca3: 'IRL',
    callingCodes: [
      '353'
    ],
    title: 'Ireland',
    loc: coord(53, -8),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: true
    }
  },
  {
    id: 'IR',
    cca3: 'IRN',
    callingCodes: [
      '98'
    ],
    title: 'Iran',
    loc: coord(32, 53)
  },
  {
    id: 'IQ',
    cca3: 'IRQ',
    callingCodes: [
      '964'
    ],
    title: 'Iraq',
    loc: coord(33, 44),
    sms: {
      senderID: SenderID.Unavailable,
      twoWaySMS: false
    }
  },
  {
    id: 'IS',
    cca3: 'ISL',
    callingCodes: [
      '354'
    ],
    title: 'Iceland',
    loc: coord(65, -18),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'IL',
    cca3: 'ISR',
    callingCodes: [
      '972'
    ],
    title: 'Israel',
    loc: coord(31.47, 35.13),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: true
    }
  },
  {
    id: 'IT',
    cca3: 'ITA',
    callingCodes: [
      '39'
    ],
    title: 'Italy',
    loc: coord(42.83, 12.83),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: true
    }
  },
  {
    id: 'JM',
    cca3: 'JAM',
    callingCodes: [
      '1876'
    ],
    title: 'Jamaica',
    loc: coord(18.25, -77.5),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'JE',
    cca3: 'JEY',
    callingCodes: [
      '44'
    ],
    title: 'Jersey',
    loc: coord(49.25, -2.17)
  },
  {
    id: 'JO',
    cca3: 'JOR',
    callingCodes: [
      '962'
    ],
    title: 'Jordan',
    loc: coord(31, 36),
    sms: {
      senderID: SenderID.PreRequisitesRequired,
      twoWaySMS: false
    }
  },
  {
    id: 'JP',
    cca3: 'JPN',
    callingCodes: [
      '81'
    ],
    title: 'Japan',
    loc: coord(36, 138),
    sms: {
      senderID: SenderID.Unavailable,
      twoWaySMS: true
    }
  },
  {
    id: 'KZ',
    cca3: 'KAZ',
    callingCodes: [
      '76',
      '77'
    ],
    title: 'Kazakhstan',
    loc: coord(48, 68),
    sms: {
      senderID: SenderID.Unavailable,
      twoWaySMS: false
    }
  },
  {
    id: 'KE',
    cca3: 'KEN',
    callingCodes: [
      '254'
    ],
    title: 'Kenya',
    loc: coord(1, 38),
    sms: {
      senderID: SenderID.Unavailable,
      twoWaySMS: false
    }
  },
  {
    id: 'KG',
    cca3: 'KGZ',
    callingCodes: [
      '996'
    ],
    title: 'Kyrgyzstan',
    loc: coord(41, 75),
    sms: {
      senderID: SenderID.Unavailable,
      twoWaySMS: false
    }
  },
  {
    id: 'KH',
    cca3: 'KHM',
    callingCodes: [
      '855'
    ],
    title: 'Cambodia',
    loc: coord(13, 105),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'KI',
    cca3: 'KIR',
    callingCodes: [
      '686'
    ],
    title: 'Kiribati',
    loc: coord(1.42, 173),
    sms: {
      senderID: SenderID.Unavailable,
      twoWaySMS: false
    }
  },
  {
    id: 'KN',
    cca3: 'KNA',
    callingCodes: [
      '1869'
    ],
    title: 'Saint Kitts and Nevis',
    loc: coord(17.33, -62.75),
    sms: {
      senderID: SenderID.Unavailable,
      twoWaySMS: false
    }
  },
  {
    id: 'KR',
    cca3: 'KOR',
    callingCodes: [
      '82'
    ],
    title: 'South Korea',
    loc: coord(37, 127.5),
    sms: {
      senderID: SenderID.Unavailable,
      twoWaySMS: false
    }
  },
  {
    id: 'XK',
    cca3: 'UNK',
    callingCodes: [
      '383'
    ],
    title: 'Kosovo',
    loc: coord(42.67, 21.17)
  },
  {
    id: 'KW',
    cca3: 'KWT',
    callingCodes: [
      '965'
    ],
    title: 'Kuwait',
    loc: coord(29.5, 45.75),
    sms: {
      senderID: SenderID.PreRequisitesRequired,
      twoWaySMS: false
    }
  },
  {
    id: 'LA',
    cca3: 'LAO',
    callingCodes: [
      '856'
    ],
    title: 'Laos',
    loc: coord(18, 105),
    sms: {
      senderID: SenderID.Unavailable,
      twoWaySMS: false
    }
  },
  {
    id: 'LB',
    cca3: 'LBN',
    callingCodes: [
      '961'
    ],
    title: 'Lebanon',
    loc: coord(33.83, 35.83),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'LR',
    cca3: 'LBR',
    callingCodes: [
      '231'
    ],
    title: 'Liberia',
    loc: coord(6.5, -9.5),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'LY',
    cca3: 'LBY',
    callingCodes: [
      '218'
    ],
    title: 'Libya',
    loc: coord(25, 17),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'LC',
    cca3: 'LCA',
    callingCodes: [
      '1758'
    ],
    title: 'Saint Lucia',
    loc: coord(13.88, -60.97),
    sms: {
      senderID: SenderID.Unavailable,
      twoWaySMS: false
    }
  },
  {
    id: 'LI',
    cca3: 'LIE',
    callingCodes: [
      '423'
    ],
    title: 'Liechtenstein',
    loc: coord(47.27, 9.53),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'LK',
    cca3: 'LKA',
    callingCodes: [
      '94'
    ],
    title: 'Sri Lanka',
    loc: coord(7, 81),
    sms: {
      senderID: SenderID.PreRequisitesRequired,
      twoWaySMS: false
    }
  },
  {
    id: 'LS',
    cca3: 'LSO',
    callingCodes: [
      '266'
    ],
    title: 'Lesotho',
    loc: coord(-29.5, 28.5),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'LT',
    cca3: 'LTU',
    callingCodes: [
      '370'
    ],
    title: 'Lithuania',
    loc: coord(56, 24),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: true
    }
  },
  {
    id: 'LU',
    cca3: 'LUX',
    callingCodes: [
      '352'
    ],
    title: 'Luxembourg',
    loc: coord(49.75, 6.17),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'LV',
    cca3: 'LVA',
    callingCodes: [
      '371'
    ],
    title: 'Latvia',
    loc: coord(57, 25),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: true
    }
  },
  {
    id: 'MO',
    cca3: 'MAC',
    callingCodes: [
      '853'
    ],
    title: 'Macau',
    loc: coord(22.17, 113.55),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'MF',
    cca3: 'MAF',
    callingCodes: [
      '590'
    ],
    title: 'Saint Martin',
    loc: coord(18.08, -63.95)
  },
  {
    id: 'MA',
    cca3: 'MAR',
    callingCodes: [
      '212'
    ],
    title: 'Morocco',
    loc: coord(32, -5),
    sms: {
      senderID: SenderID.Unavailable,
      twoWaySMS: false
    }
  },
  {
    id: 'MC',
    cca3: 'MCO',
    callingCodes: [
      '377'
    ],
    title: 'Monaco',
    loc: coord(43.73, 7.4),
    sms: {
      senderID: SenderID.Unavailable,
      twoWaySMS: false
    }
  },
  {
    id: 'MD',
    cca3: 'MDA',
    callingCodes: [
      '373'
    ],
    title: 'Moldova',
    loc: coord(47, 29),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'MG',
    cca3: 'MDG',
    callingCodes: [
      '261'
    ],
    title: 'Madagascar',
    loc: coord(-20, 47),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'MV',
    cca3: 'MDV',
    callingCodes: [
      '960'
    ],
    title: 'Maldives',
    loc: coord(3.25, 73),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'MX',
    cca3: 'MEX',
    callingCodes: [
      '52'
    ],
    title: 'Mexico',
    loc: coord(23, -102),
    sms: {
      senderID: SenderID.Unavailable,
      twoWaySMS: true
    }
  },
  {
    id: 'MH',
    cca3: 'MHL',
    callingCodes: [
      '692'
    ],
    title: 'Marshall Islands',
    loc: coord(9, 168)
  },
  {
    id: 'MK',
    cca3: 'MKD',
    callingCodes: [
      '389'
    ],
    title: 'North Macedonia',
    loc: coord(41.83, 22),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'ML',
    cca3: 'MLI',
    callingCodes: [
      '223'
    ],
    title: 'Mali',
    loc: coord(17, -4),
    sms: {
      senderID: SenderID.Unavailable,
      twoWaySMS: false
    }
  },
  {
    id: 'MT',
    cca3: 'MLT',
    callingCodes: [
      '356'
    ],
    title: 'Malta',
    loc: coord(35.83, 14.58),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'MM',
    cca3: 'MMR',
    callingCodes: [
      '95'
    ],
    title: 'Myanmar',
    loc: coord(22, 98),
    sms: {
      senderID: SenderID.Unavailable,
      twoWaySMS: false
    }
  },
  {
    id: 'ME',
    cca3: 'MNE',
    callingCodes: [
      '382'
    ],
    title: 'Montenegro',
    loc: coord(42.5, 19.3),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'MN',
    cca3: 'MNG',
    callingCodes: [
      '976'
    ],
    title: 'Mongolia',
    loc: coord(46, 105),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'MP',
    cca3: 'MNP',
    callingCodes: [
      '1670'
    ],
    title: 'Northern Mariana Islands',
    loc: coord(15.2, 145.75)
  },
  {
    id: 'MZ',
    cca3: 'MOZ',
    callingCodes: [
      '258'
    ],
    title: 'Mozambique',
    loc: coord(-18.25, 35),
    sms: {
      senderID: SenderID.Unavailable,
      twoWaySMS: false
    }
  },
  {
    id: 'MR',
    cca3: 'MRT',
    callingCodes: [
      '222'
    ],
    title: 'Mauritania',
    loc: coord(20, -12),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'MS',
    cca3: 'MSR',
    callingCodes: [
      '1664'
    ],
    title: 'Montserrat',
    loc: coord(16.75, -62.2),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'MQ',
    cca3: 'MTQ',
    callingCodes: [
      '596'
    ],
    title: 'Martinique',
    loc: coord(14.67, -61),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'MU',
    cca3: 'MUS',
    callingCodes: [
      '230'
    ],
    title: 'Mauritius',
    loc: coord(-20.28, 57.55),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'MW',
    cca3: 'MWI',
    callingCodes: [
      '265'
    ],
    title: 'Malawi',
    loc: coord(-13.5, 34),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'MY',
    cca3: 'MYS',
    callingCodes: [
      '60'
    ],
    title: 'Malaysia',
    loc: coord(2.5, 112.5),
    sms: {
      senderID: SenderID.Unavailable,
      twoWaySMS: true
    }
  },
  {
    id: 'YT',
    cca3: 'MYT',
    callingCodes: [
      '262'
    ],
    title: 'Mayotte',
    loc: coord(-12.83, 45.17)
  },
  {
    id: 'NA',
    cca3: 'NAM',
    callingCodes: [
      '264'
    ],
    title: 'Namibia',
    loc: coord(-22, 17),
    sms: {
      senderID: SenderID.Unavailable,
      twoWaySMS: false
    }
  },
  {
    id: 'NC',
    cca3: 'NCL',
    callingCodes: [
      '687'
    ],
    title: 'New Caledonia',
    loc: coord(-21.5, 165.5),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'NE',
    cca3: 'NER',
    callingCodes: [
      '227'
    ],
    title: 'Niger',
    loc: coord(16, 8),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'NF',
    cca3: 'NFK',
    callingCodes: [
      '672'
    ],
    title: 'Norfolk Island',
    loc: coord(-29.03, 167.95)
  },
  {
    id: 'NG',
    cca3: 'NGA',
    callingCodes: [
      '234'
    ],
    title: 'Nigeria',
    loc: coord(10, 8),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'NI',
    cca3: 'NIC',
    callingCodes: [
      '505'
    ],
    title: 'Nicaragua',
    loc: coord(13, -85),
    sms: {
      senderID: SenderID.Unavailable,
      twoWaySMS: false
    }
  },
  {
    id: 'NU',
    cca3: 'NIU',
    callingCodes: [
      '683'
    ],
    title: 'Niue',
    loc: coord(-19.03, -169.87)
  },
  {
    id: 'NL',
    cca3: 'NLD',
    callingCodes: [
      '31'
    ],
    title: 'Netherlands',
    loc: coord(52.5, 5.75),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: true
    }
  },
  {
    id: 'NO',
    cca3: 'NOR',
    callingCodes: [
      '47'
    ],
    title: 'Norway',
    loc: coord(62, 10),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: true
    }
  },
  {
    id: 'NP',
    cca3: 'NPL',
    callingCodes: [
      '977'
    ],
    title: 'Nepal',
    loc: coord(28, 84),
    sms: {
      senderID: SenderID.Unavailable,
      twoWaySMS: false
    }
  },
  {
    id: 'NR',
    cca3: 'NRU',
    callingCodes: [
      '674'
    ],
    title: 'Nauru',
    loc: coord(-0.53, 166.92)
  },
  {
    id: 'NZ',
    cca3: 'NZL',
    callingCodes: [
      '64'
    ],
    title: 'New Zealand',
    loc: coord(-41, 174),
    sms: {
      senderID: SenderID.Unavailable,
      twoWaySMS: true
    }
  },
  {
    id: 'OM',
    cca3: 'OMN',
    callingCodes: [
      '968'
    ],
    title: 'Oman',
    loc: coord(21, 57),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'PK',
    cca3: 'PAK',
    callingCodes: [
      '92'
    ],
    title: 'Pakistan',
    loc: coord(30, 70),
    sms: {
      senderID: SenderID.Unavailable,
      twoWaySMS: false
    }
  },
  {
    id: 'PA',
    cca3: 'PAN',
    callingCodes: [
      '507'
    ],
    title: 'Panama',
    loc: coord(9, -80),
    sms: {
      senderID: SenderID.Unavailable,
      twoWaySMS: false
    }
  },
  {
    id: 'PN',
    cca3: 'PCN',
    callingCodes: [
      '64'
    ],
    title: 'Pitcairn Islands',
    loc: coord(-25.07, -130.1)
  },
  {
    id: 'PE',
    cca3: 'PER',
    callingCodes: [
      '51'
    ],
    title: 'Peru',
    loc: coord(-10, -76),
    sms: {
      senderID: SenderID.Unavailable,
      twoWaySMS: false
    }
  },
  {
    id: 'PH',
    cca3: 'PHL',
    callingCodes: [
      '63'
    ],
    title: 'Philippines',
    loc: coord(13, 122),
    sms: {
      senderID: SenderID.PreRequisitesRequired,
      twoWaySMS: true
    }
  },
  {
    id: 'PW',
    cca3: 'PLW',
    callingCodes: [
      '680'
    ],
    title: 'Palau',
    loc: coord(7.5, 134.5),
    sms: {
      senderID: SenderID.Unavailable,
      twoWaySMS: false
    }
  },
  {
    id: 'PG',
    cca3: 'PNG',
    callingCodes: [
      '675'
    ],
    title: 'Papua New Guinea',
    loc: coord(-6, 147),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'PL',
    cca3: 'POL',
    callingCodes: [
      '48'
    ],
    title: 'Poland',
    loc: coord(52, 20),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: true
    }
  },
  {
    id: 'PR',
    cca3: 'PRI',
    callingCodes: [
      '1787',
      '1939'
    ],
    title: 'Puerto Rico',
    loc: coord(18.25, -66.5),
    sms: {
      senderID: SenderID.Unavailable,
      twoWaySMS: true
    }
  },
  {
    id: 'KP',
    cca3: 'PRK',
    callingCodes: [
      '850'
    ],
    title: 'North Korea',
    loc: coord(40, 127)
  },
  {
    id: 'PT',
    cca3: 'PRT',
    callingCodes: [
      '351'
    ],
    title: 'Portugal',
    loc: coord(39.5, -8),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: true
    }
  },
  {
    id: 'PY',
    cca3: 'PRY',
    callingCodes: [
      '595'
    ],
    title: 'Paraguay',
    loc: coord(-23, -58),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'PS',
    cca3: 'PSE',
    callingCodes: [
      '970'
    ],
    title: 'Palestine',
    loc: coord(31.9, 35.2),
    sms: {
      senderID: SenderID.Unavailable,
      twoWaySMS: false
    }
  },
  {
    id: 'PF',
    cca3: 'PYF',
    callingCodes: [
      '689'
    ],
    title: 'French Polynesia',
    loc: coord(-15, -140)
  },
  {
    id: 'QA',
    cca3: 'QAT',
    callingCodes: [
      '974'
    ],
    title: 'Qatar',
    loc: coord(25.5, 51.25),
    sms: {
      senderID: SenderID.PreRequisitesRequired,
      twoWaySMS: false
    }
  },
  {
    id: 'RE',
    cca3: 'REU',
    callingCodes: [
      '262'
    ],
    title: 'Réunion',
    loc: coord(-21.15, 55.5),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'RO',
    cca3: 'ROU',
    callingCodes: [
      '40'
    ],
    title: 'Romania',
    loc: coord(46, 25),
    sms: {
      senderID: SenderID.Unavailable,
      twoWaySMS: true
    }
  },
  {
    id: 'RU',
    cca3: 'RUS',
    callingCodes: [
      '73',
      '74',
      '75',
      '78',
      '79'
    ],
    title: 'Russia',
    loc: coord(60, 100),
    sms: {
      senderID: SenderID.PreRequisitesRequired,
      twoWaySMS: true
    }
  },
  {
    id: 'RW',
    cca3: 'RWA',
    callingCodes: [
      '250'
    ],
    title: 'Rwanda',
    loc: coord(-2, 30),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'SA',
    cca3: 'SAU',
    callingCodes: [
      '966'
    ],
    title: 'Saudi Arabia',
    loc: coord(25, 45),
    sms: {
      senderID: SenderID.PreRequisitesRequired,
      twoWaySMS: false
    }
  },
  {
    id: 'SD',
    cca3: 'SDN',
    callingCodes: [
      '249'
    ],
    title: 'Sudan',
    loc: coord(15, 30)
  },
  {
    id: 'SN',
    cca3: 'SEN',
    callingCodes: [
      '221'
    ],
    title: 'Senegal',
    loc: coord(14, -14),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'SG',
    cca3: 'SGP',
    callingCodes: [
      '65'
    ],
    title: 'Singapore',
    loc: coord(1.37, 103.8),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: true
    }
  },
  {
    id: 'GS',
    cca3: 'SGS',
    callingCodes: [
      '500'
    ],
    title: 'South Georgia',
    loc: coord(-54.5, -37)
  },
  {
    id: 'SJ',
    cca3: 'SJM',
    callingCodes: [
      '4779'
    ],
    title: 'Svalbard and Jan Mayen',
    loc: coord(78, 20)
  },
  {
    id: 'SB',
    cca3: 'SLB',
    callingCodes: [
      '677'
    ],
    title: 'Solomon Islands',
    loc: coord(-8, 159),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'SL',
    cca3: 'SLE',
    callingCodes: [
      '232'
    ],
    title: 'Sierra Leone',
    loc: coord(8.5, -11.5),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'SV',
    cca3: 'SLV',
    callingCodes: [
      '503'
    ],
    title: 'El Salvador',
    loc: coord(13.83, -88.92),
    sms: {
      senderID: SenderID.Unavailable,
      twoWaySMS: false
    }
  },
  {
    id: 'SM',
    cca3: 'SMR',
    callingCodes: [
      '378'
    ],
    title: 'San Marino',
    loc: coord(43.77, 12.42)
  },
  {
    id: 'SO',
    cca3: 'SOM',
    callingCodes: [
      '252'
    ],
    title: 'Somalia',
    loc: coord(10, 49),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'PM',
    cca3: 'SPM',
    callingCodes: [
      '508'
    ],
    title: 'Saint Pierre and Miquelon',
    loc: coord(46.83, -56.33)
  },
  {
    id: 'RS',
    cca3: 'SRB',
    callingCodes: [
      '381'
    ],
    title: 'Serbia',
    loc: coord(44, 21),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'SS',
    cca3: 'SSD',
    callingCodes: [
      '211'
    ],
    title: 'South Sudan',
    loc: coord(7, 30),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'ST',
    cca3: 'STP',
    callingCodes: [
      '239'
    ],
    title: 'São Tomé and Príncipe',
    loc: coord(1, 7),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'SR',
    cca3: 'SUR',
    callingCodes: [
      '597'
    ],
    title: 'Suriname',
    loc: coord(4, -56),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'SK',
    cca3: 'SVK',
    callingCodes: [
      '421'
    ],
    title: 'Slovakia',
    loc: coord(48.67, 19.5),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: true
    }
  },
  {
    id: 'SI',
    cca3: 'SVN',
    callingCodes: [
      '386'
    ],
    title: 'Slovenia',
    loc: coord(46.12, 14.82),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: true
    }
  },
  {
    id: 'SE',
    cca3: 'SWE',
    callingCodes: [
      '46'
    ],
    title: 'Sweden',
    loc: coord(62, 15),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: true
    }
  },
  {
    id: 'SZ',
    cca3: 'SWZ',
    callingCodes: [
      '268'
    ],
    title: 'Eswatini',
    loc: coord(-26.5, 31.5),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'SX',
    cca3: 'SXM',
    callingCodes: [
      '1721'
    ],
    title: 'Sint Maarten',
    loc: coord(18.03, -63.05)
  },
  {
    id: 'SC',
    cca3: 'SYC',
    callingCodes: [
      '248'
    ],
    title: 'Seychelles',
    loc: coord(-4.58, 55.67),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'SY',
    cca3: 'SYR',
    callingCodes: [
      '963'
    ],
    title: 'Syria',
    loc: coord(35, 38)
  },
  {
    id: 'TC',
    cca3: 'TCA',
    callingCodes: [
      '1649'
    ],
    title: 'Turks and Caicos Islands',
    loc: coord(21.75, -71.58),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'TD',
    cca3: 'TCD',
    callingCodes: [
      '235'
    ],
    title: 'Chad',
    loc: coord(15, 19),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'TG',
    cca3: 'TGO',
    callingCodes: [
      '228'
    ],
    title: 'Togo',
    loc: coord(8, 1.17),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'TH',
    cca3: 'THA',
    callingCodes: [
      '66'
    ],
    title: 'Thailand',
    loc: coord(15, 100),
    sms: {
      senderID: SenderID.PreRequisitesRequired,
      twoWaySMS: true
    }
  },
  {
    id: 'TJ',
    cca3: 'TJK',
    callingCodes: [
      '992'
    ],
    title: 'Tajikistan',
    loc: coord(39, 71),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'TK',
    cca3: 'TKL',
    callingCodes: [
      '690'
    ],
    title: 'Tokelau',
    loc: coord(-9, -172)
  },
  {
    id: 'TM',
    cca3: 'TKM',
    callingCodes: [
      '993'
    ],
    title: 'Turkmenistan',
    loc: coord(40, 60),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'TL',
    cca3: 'TLS',
    callingCodes: [
      '670'
    ],
    title: 'Timor-Leste',
    loc: coord(-8.83, 125.92),
    sms: {
      senderID: SenderID.Unavailable,
      twoWaySMS: false
    }
  },
  {
    id: 'TO',
    cca3: 'TON',
    callingCodes: [
      '676'
    ],
    title: 'Tonga',
    loc: coord(-20, -175),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'TT',
    cca3: 'TTO',
    callingCodes: [
      '1868'
    ],
    title: 'Trinidad and Tobago',
    loc: coord(11, -61),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'TN',
    cca3: 'TUN',
    callingCodes: [
      '216'
    ],
    title: 'Tunisia',
    loc: coord(34, 9),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'TR',
    cca3: 'TUR',
    callingCodes: [
      '90'
    ],
    title: 'Turkey',
    loc: coord(39, 35),
    sms: {
      senderID: SenderID.PreRequisitesRequired,
      twoWaySMS: false
    }
  },
  {
    id: 'TV',
    cca3: 'TUV',
    callingCodes: [
      '688'
    ],
    title: 'Tuvalu',
    loc: coord(-8, 178)
  },
  {
    id: 'TW',
    cca3: 'TWN',
    callingCodes: [
      '886'
    ],
    title: 'Taiwan',
    loc: coord(23.5, 121),
    sms: {
      senderID: SenderID.Unavailable,
      twoWaySMS: true
    }
  },
  {
    id: 'TZ',
    cca3: 'TZA',
    callingCodes: [
      '255'
    ],
    title: 'Tanzania',
    loc: coord(-6, 35),
    sms: {
      senderID: SenderID.Unavailable,
      twoWaySMS: false
    }
  },
  {
    id: 'UG',
    cca3: 'UGA',
    callingCodes: [
      '256'
    ],
    title: 'Uganda',
    loc: coord(1, 32),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'UA',
    cca3: 'UKR',
    callingCodes: [
      '380'
    ],
    title: 'Ukraine',
    loc: coord(49, 32),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: true
    }
  },
  {
    id: 'UM',
    cca3: 'UMI',
    callingCodes: [
      '268'
    ],
    title: 'United States Minor Outlying Islands',
    loc: coord(19.3, 166.63)
  },
  {
    id: 'UY',
    cca3: 'URY',
    callingCodes: [
      '598'
    ],
    title: 'Uruguay',
    loc: coord(-33, -56),
    sms: {
      senderID: SenderID.Unavailable,
      twoWaySMS: false
    }
  },
  {
    id: 'US',
    cca3: 'USA',
    callingCodes: [
      '1201',
      '1202',
      '1203',
      '1205',
      '1206',
      '1207',
      '1208',
      '1209',
      '1210',
      '1212',
      '1213',
      '1214',
      '1215',
      '1216',
      '1217',
      '1218',
      '1219',
      '1220',
      '1224',
      '1225',
      '1227',
      '1228',
      '1229',
      '1231',
      '1234',
      '1239',
      '1240',
      '1248',
      '1251',
      '1252',
      '1253',
      '1254',
      '1256',
      '1260',
      '1262',
      '1267',
      '1269',
      '1270',
      '1272',
      '1274',
      '1276',
      '1281',
      '1283',
      '1301',
      '1302',
      '1303',
      '1304',
      '1305',
      '1307',
      '1308',
      '1309',
      '1310',
      '1312',
      '1313',
      '1314',
      '1315',
      '1316',
      '1317',
      '1318',
      '1319',
      '1320',
      '1321',
      '1323',
      '1325',
      '1327',
      '1330',
      '1331',
      '1334',
      '1336',
      '1337',
      '1339',
      '1346',
      '1347',
      '1351',
      '1352',
      '1360',
      '1361',
      '1364',
      '1380',
      '1385',
      '1386',
      '1401',
      '1402',
      '1404',
      '1405',
      '1406',
      '1407',
      '1408',
      '1409',
      '1410',
      '1412',
      '1413',
      '1414',
      '1415',
      '1417',
      '1419',
      '1423',
      '1424',
      '1425',
      '1430',
      '1432',
      '1434',
      '1435',
      '1440',
      '1442',
      '1443',
      '1447',
      '1458',
      '1463',
      '1464',
      '1469',
      '1470',
      '1475',
      '1478',
      '1479',
      '1480',
      '1484',
      '1501',
      '1502',
      '1503',
      '1504',
      '1505',
      '1507',
      '1508',
      '1509',
      '1510',
      '1512',
      '1513',
      '1515',
      '1516',
      '1517',
      '1518',
      '1520',
      '1530',
      '1531',
      '1534',
      '1539',
      '1540',
      '1541',
      '1551',
      '1559',
      '1561',
      '1562',
      '1563',
      '1564',
      '1567',
      '1570',
      '1571',
      '1573',
      '1574',
      '1575',
      '1580',
      '1585',
      '1586',
      '1601',
      '1602',
      '1603',
      '1605',
      '1606',
      '1607',
      '1608',
      '1609',
      '1610',
      '1612',
      '1614',
      '1615',
      '1616',
      '1617',
      '1618',
      '1619',
      '1620',
      '1623',
      '1626',
      '1628',
      '1629',
      '1630',
      '1631',
      '1636',
      '1641',
      '1646',
      '1650',
      '1651',
      '1657',
      '1660',
      '1661',
      '1662',
      '1667',
      '1669',
      '1678',
      '1681',
      '1682',
      '1701',
      '1702',
      '1703',
      '1704',
      '1706',
      '1707',
      '1708',
      '1712',
      '1713',
      '1714',
      '1715',
      '1716',
      '1717',
      '1718',
      '1719',
      '1720',
      '1724',
      '1725',
      '1727',
      '1730',
      '1731',
      '1732',
      '1734',
      '1737',
      '1740',
      '1743',
      '1747',
      '1754',
      '1757',
      '1760',
      '1762',
      '1763',
      '1765',
      '1769',
      '1770',
      '1772',
      '1773',
      '1774',
      '1775',
      '1779',
      '1781',
      '1785',
      '1786',
      '1801',
      '1802',
      '1803',
      '1804',
      '1805',
      '1806',
      '1808',
      '1810',
      '1812',
      '1813',
      '1814',
      '1815',
      '1816',
      '1817',
      '1818',
      '1828',
      '1830',
      '1831',
      '1832',
      '1843',
      '1845',
      '1847',
      '1848',
      '1850',
      '1854',
      '1856',
      '1857',
      '1858',
      '1859',
      '1860',
      '1862',
      '1863',
      '1864',
      '1865',
      '1870',
      '1872',
      '1878',
      '1901',
      '1903',
      '1904',
      '1906',
      '1907',
      '1908',
      '1909',
      '1910',
      '1912',
      '1913',
      '1914',
      '1915',
      '1916',
      '1917',
      '1918',
      '1919',
      '1920',
      '1925',
      '1928',
      '1929',
      '1930',
      '1931',
      '1934',
      '1936',
      '1937',
      '1938',
      '1940',
      '1941',
      '1947',
      '1949',
      '1951',
      '1952',
      '1954',
      '1956',
      '1959',
      '1970',
      '1971',
      '1972',
      '1973',
      '1975',
      '1978',
      '1979',
      '1980',
      '1984',
      '1985',
      '1989'
    ],
    title: 'United States',
    loc: coord(38, -97),
    sms: {
      senderID: SenderID.Unavailable,
      twoWaySMS: true
    }
  },
  {
    id: 'UZ',
    cca3: 'UZB',
    callingCodes: [
      '998'
    ],
    title: 'Uzbekistan',
    loc: coord(41, 64),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'VA',
    cca3: 'VAT',
    callingCodes: [
      '3906698',
      '379'
    ],
    title: 'Vatican City',
    loc: coord(41.9, 12.45)
  },
  {
    id: 'VC',
    cca3: 'VCT',
    callingCodes: [
      '1784'
    ],
    title: 'Saint Vincent and the Grenadines',
    loc: coord(13.25, -61.2),
    sms: {
      senderID: SenderID.Unavailable,
      twoWaySMS: false
    }
  },
  {
    id: 'VE',
    cca3: 'VEN',
    callingCodes: [
      '58'
    ],
    title: 'Venezuela',
    loc: coord(8, -66),
    sms: {
      senderID: SenderID.Unavailable,
      twoWaySMS: false
    }
  },
  {
    id: 'VG',
    cca3: 'VGB',
    callingCodes: [
      '1284'
    ],
    title: 'British Virgin Islands',
    loc: coord(18.43, -64.62),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'VI',
    cca3: 'VIR',
    callingCodes: [
      '1340'
    ],
    title: 'United States Virgin Islands',
    loc: coord(18.35, -64.93),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'VN',
    cca3: 'VNM',
    callingCodes: [
      '84'
    ],
    title: 'Vietnam',
    loc: coord(16.17, 107.83),
    sms: {
      senderID: SenderID.PreRequisitesRequired,
      twoWaySMS: false
    }
  },
  {
    id: 'VU',
    cca3: 'VUT',
    callingCodes: [
      '678'
    ],
    title: 'Vanuatu',
    loc: coord(-16, 167),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'WF',
    cca3: 'WLF',
    callingCodes: [
      '681'
    ],
    title: 'Wallis and Futuna',
    loc: coord(-13.3, -176.2)
  },
  {
    id: 'WS',
    cca3: 'WSM',
    callingCodes: [
      '685'
    ],
    title: 'Samoa',
    loc: coord(-13.58, -172.33),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'YE',
    cca3: 'YEM',
    callingCodes: [
      '967'
    ],
    title: 'Yemen',
    loc: coord(15, 48),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'ZA',
    cca3: 'ZAF',
    callingCodes: [
      '27'
    ],
    title: 'South Africa',
    loc: coord(-29, 24),
    sms: {
      senderID: SenderID.Unavailable,
      twoWaySMS: true
    }
  },
  {
    id: 'ZM',
    cca3: 'ZMB',
    callingCodes: [
      '260'
    ],
    title: 'Zambia',
    loc: coord(-15, 30),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  },
  {
    id: 'ZW',
    cca3: 'ZWE',
    callingCodes: [
      '263'
    ],
    title: 'Zimbabwe',
    loc: coord(-20, 30),
    sms: {
      senderID: SenderID.Available,
      twoWaySMS: false
    }
  }
] as Country[]
export const LONGEST_CALLING_CODE = 7

/**
 * Known geographical locations of aws regions
 */
export const getRegions = () => [
  {
    code: 'us-east-1',
    partition: Partition.Default,
    idx: '0',
    loc: coord(38.99, -77.45)
  },
  {
    code: 'us-east-2',
    partition: Partition.Default,
    idx: '1',
    loc: coord(40.09, -82.75)
  },
  {
    code: 'us-west-1',
    partition: Partition.Default,
    idx: '2',
    loc: coord(37.44, -122.15)
  },
  {
    code: 'us-west-2',
    partition: Partition.Default,
    idx: '3',
    loc: coord(45.92, -119.27)
  },
  {
    code: 'ca-central-1',
    partition: Partition.Default,
    idx: '4',
    loc: coord(45.5, -73.6)
  },
  {
    code: 'ap-south-1',
    partition: Partition.Default,
    idx: '5',
    loc: coord(19.24, 72.97)
  },
  {
    code: 'ap-northeast-1',
    partition: Partition.Default,
    idx: '6',
    loc: coord(35.62, 139.75)
  },
  {
    code: 'ap-northeast-2',
    partition: Partition.Default,
    idx: '7',
    loc: coord(37.56, 126.87)
  },
  {
    code: 'ap-northeast-3',
    partition: Partition.Default,
    idx: '8',
    loc: coord(34.69, 135.5)
  },
  {
    code: 'ap-southeast-1',
    partition: Partition.Default,
    idx: '9',
    loc: coord(1.32, 103.69)
  },
  {
    code: 'ap-southeast-2',
    partition: Partition.Default,
    idx: 'a',
    loc: coord(-33.91, 151.19)
  },
  {
    code: 'cn-north-1',
    partition: Partition.China,
    idx: 'b',
    loc: coord(39.81, 116.58),
    fallback: {
      ses: null
    }
  },
  {
    code: 'cn-northwest-1',
    partition: Partition.China,
    idx: 'c',
    loc: coord(37.5, 105.16),
    fallback: {
      ses: null
    }
  },
  {
    code: 'eu-central-1',
    partition: Partition.Default,
    idx: 'd',
    loc: coord(50.1, 8.63)
  },
  {
    code: 'eu-west-1',
    partition: Partition.Default,
    idx: 'e',
    loc: coord(53.41, -6.22)
  },
  {
    code: 'eu-west-2',
    partition: Partition.Default,
    idx: 'f',
    loc: coord(51.51, -0.06)
  },
  {
    code: 'eu-west-3',
    partition: Partition.Default,
    idx: 'g',
    loc: coord(48.6, 2.3)
  },
  {
    code: 'eu-north-1',
    partition: Partition.Default,
    idx: 'h',
    loc: coord(59.33, 17.84)
  },
  {
    code: 'ap-east-1',
    partition: Partition.Default,
    idx: 'i',
    loc: coord(22.29, 114.27),
    fallback: {
      ses: 'ap-northeast-2'
    }
  },
  {
    code: 'sa-east-1',
    partition: Partition.Default,
    idx: 'j',
    loc: coord(-23.49, -46.81)
  },
  {
    code: 'me-south-1',
    partition: Partition.Default,
    idx: 'k',
    loc: coord(25.94, 50.31)
  },
  {
    code: 'ap-southeast-3',
    partition: Partition.Default,
    idx: 'l',
    loc: coord(-6.2, 106.82),
    fallback: {
      ses: 'ap-southeast-1'
    }
  },
  {
    code: 'us-gov-west-1',
    partition: Partition.UsGov,
    idx: 'm',
    loc: coord(37.44, -122.15)
  },
  {
    code: 'eu-south-1',
    partition: Partition.Default,
    idx: 'n',
    loc: coord(45.46, 9.11)
  },
  {
    code: 'us-gov-east-1',
    partition: Partition.UsGov,
    idx: 'o',
    loc: coord(38.99, -77.45),
    fallback: {
      ses: 'us-gov-west-1'
    }
  },
  {
    code: 'af-south-1',
    partition: Partition.Default,
    idx: 'p',
    loc: coord(-33.91, 18.38)
  }
] as Region[]

